linuxdeepin/deepin-devicemanager

- debian/changelog
- deepin-devicemanager/src/DeviceManager/DeviceManager.cpp
- deepin-devicemanager/src/DeviceManager/DeviceManager.h
- deepin-devicemanager/src/DeviceManager/DeviceMonitor.cpp
- deepin-devicemanager/src/DeviceManager/DeviceNetwork.cpp
- deepin-devicemanager/src/DeviceManager/DeviceNetwork.h
- deepin-devicemanager/src/GenerateDevice/DeviceFactory.cpp
- deepin-devicemanager/src/GenerateDevice/HWGenerator.cpp
- deepin-devicemanager/src/GenerateDevice/KLVGenerator.cpp
- deepin-devicemanager/src/GenerateDevice/KLVGenerator.h
> fix: 过滤HW的虚拟网卡信息

- deepin-devicemanager/src/GenerateDevice/HWGenerator.cpp
概况里从dmi获取系统信息
Log: 概况里从dmi获取系统信息
> fix: 概况里从dmi获取系统信息

- deepin-devicemanager/src/GenerateDevice/KLVGenerator.cpp
- deepin-devicemanager/src/GenerateDevice/KLVGenerator.h
> fix: 调整hw硬盘信息

- deepin-devicemanager/src/DeviceManager/DeviceManager.cpp
- deepin-devicemanager/src/DeviceManager/DeviceManager.h
- deepin-devicemanager/src/DeviceManager/DeviceStorage.cpp
- deepin-devicemanager/src/DeviceManager/DeviceStorage.h
- deepin-devicemanager/src/GenerateDevice/HWGenerator.cpp
- deepin-devicemanager/src/GenerateDevice/HWGenerator.h
> fix: 将磁盘大小取整

- deepin-devicemanager-server/src/LoadInfo/ThreadPool.cpp
- deepin-devicemanager/src/commonfunction.cpp
- deepin-devicemanager/src/commonfunction.h
> fix: 添加dmi读取系统名称

- deepin-devicemanager-server/src/MainJob.cpp
取消开机驱动安装提示
Log: 取消开机驱动安装提示
Task: https://pms.uniontech.com/story-view-18351.html
/review @pengfeixx @feeengli
> feat: 取消开机驱动安装提示

- deepin-devicemanager/src/SingleDeviceManager.cpp
- deepin-devicemanager/src/Tool/eventlogutils.cpp
- deepin-devicemanager/src/Tool/eventlogutils.h
> feat: 数据埋点

- deepin-devicemanager/src/GenerateDevice/DeviceGenerator.h
- deepin-devicemanager/src/GenerateDevice/KLVGenerator.cpp
- deepin-devicemanager/src/GenerateDevice/KLVGenerator.h
去掉图形设备中制造商
Log: 去掉图形设备中制造商
Bug: https://pms.uniontech.com/bug-view-151715.html
/review @pengfeixx @feeengli @jeffshuai @hundundadi
> fix: 图形设备中制造商实际显示信息与预期显示信息不符

- deepin-devicemanager-server/src/DriverControl/DriverInstaller.cpp
use std:string to replace string
Log: fix build failed
> fix: build failed

- deepin-devicemanager/src/DeviceManager/DeviceAudio.cpp
- deepin-devicemanager/src/DeviceManager/DeviceAudio.h
- deepin-devicemanager/src/DeviceManager/DeviceInfo.cpp
- deepin-devicemanager/src/DeviceManager/DeviceInfo.h
- deepin-devicemanager/src/DeviceManager/DeviceManager.cpp
- deepin-devicemanager/src/DeviceManager/DeviceManager.h
- deepin-devicemanager/src/GenerateDevice/CmdTool.cpp
- deepin-devicemanager/src/GenerateDevice/DeviceGenerator.cpp
- deepin-devicemanager/src/GenerateDevice/DeviceGenerator.h
板载声卡 hwinfo和 lshw都识别不了，只有 aplay -l能识别，bug-141423
Log: 修复板载声卡从sys_class_sound识别并加载芯片信息
> fix: 板载声卡识别

- deepin-devicemanager-server/CMakeLists.txt
- deepin-devicemanager-server/src/DriverControl/DriverDBusInterface.cpp
- deepin-devicemanager-server/tests/CMakeLists.txt
打开设备管理器情况下提示权限对话框
Log: 非root账户需用输入密码才能安装、卸载驱动
> fix: dbus接口安装或卸载任意驱动

- deepin-devicemanager-server/src/DriverControl/DriverDBusInterface.cpp
限制apt安装驱动
Log: 限制apt安装驱动
@lzwind @feeengli @myk1343 @hundundadi
> fix: 未限制apt安装驱动

- deepin-devicemanager/src/Page/MainWindow.cpp
- deepin-devicemanager/src/Page/PageDriverManager.cpp
- deepin-devicemanager/src/Page/PageDriverManager.h
扫描驱动前先扫描设备
Log: 正常识别驱动
Bug: https://pms.uniontech.com/bug-view-131857.html
> fix: 插入新设备点击重新检测按钮扫描无法识别

- deepin-devicemanager/src/DeviceManager/DeviceGpu.cpp
- deepin-devicemanager/src/DeviceManager/DeviceGpu.h
- deepin-devicemanager/src/DeviceManager/DeviceManager.cpp
- deepin-devicemanager/src/DeviceManager/DeviceManager.h
- deepin-devicemanager/src/GenerateDevice/CmdTool.cpp
- deepin-devicemanager/src/GenerateDevice/DeviceGenerator.cpp
- deepin-devicemanager/tests/src/DeviceManager/ut_devicegpu.cpp
- deepin-devicemanager/tests/src/DeviceManager/ut_devicemanager.cpp
通过smi读取显卡显存
Log: 正常显示显卡显存
Bug: https://pms.uniontech.com/bug-view-151025.html
/review @lzwind @feeengli @myk1343 @hundundadi
> fix: 英伟达显卡设备管理器中无显存显示

- deepin-devicemanager/src/DeviceManager/DeviceGpu.cpp
添加读取N卡名称
Log: 显示N卡名称
/review @lzwind @feeengli @myk1343 @hundundadi
> fix: N卡名称错误

- deepin-devicemanager/src/Widget/drivertableview.cpp
使用DGuiApplicationHelper获取palette
Log: 使用DGuiApplicationHelper获取palette
> fix: 使用DGuiApplicationHelper获取palette

- deepin-devicemanager/src/GenerateDevice/LoadInfoThread.cpp
> fix: 加大初始化设备读取时间

- deepin-devicemanager-server/src/LoadInfo/ThreadPool.cpp
- deepin-devicemanager-server/src/MainJob.cpp
Log: 添加服务的读取设备时间
/review @lzwind @feeengli @hundundadi @myk1343 @HeeMingYang
> fix: 添加服务的读取设备时间

- deepin-devicemanager-server/src/MainJob.cpp
- deepin-devicemanager-server/src/MainJob.h
驱动管理延迟加载
Log: 正常启动设备管理器
/review @lzwind @feeengli @myk1343 @hundundadi @jeffshuai
> fix: 驱动管理启动时加载时间过长

- deepin-devicemanager-server/src/MainJob.cpp
延迟网络加载驱动信息
Log: 正常显示设备信息
Bug: https://pms.uniontech.com/bug-view-146857.html
/review @lzwind @myk1343 @feeengli @jeffshuai @hundundadi
> fix: 设备管理器只有概况信息

- deepin-devicemanager/translations/deepin-devicemanager_az.ts
- deepin-devicemanager/translations/deepin-devicemanager_ca.ts
- deepin-devicemanager/translations/deepin-devicemanager_de.ts
- deepin-devicemanager/translations/deepin-devicemanager_es.ts
- deepin-devicemanager/translations/deepin-devicemanager_fi.ts
- deepin-devicemanager/translations/deepin-devicemanager_fr.ts
- deepin-devicemanager/translations/deepin-devicemanager_hu.ts
- deepin-devicemanager/translations/deepin-devicemanager_it.ts
- deepin-devicemanager/translations/deepin-devicemanager_ms.ts
- deepin-devicemanager/translations/deepin-devicemanager_nl.ts
- deepin-devicemanager/translations/deepin-devicemanager_pl.ts
- deepin-devicemanager/translations/deepin-devicemanager_pt_BR.ts
- deepin-devicemanager/translations/deepin-devicemanager_ru.ts
- deepin-devicemanager/translations/deepin-devicemanager_sq.ts
- deepin-devicemanager/translations/deepin-devicemanager_tr.ts
- deepin-devicemanager/translations/deepin-devicemanager_uk.ts
更新翻译文件
Log: 更新翻译文件
/review @lzwind @pengfeixx @jeffshuai @HeeMingYang @feeengli @hualet @myk1343
> chore: 更新翻译文件

- deepin-devicemanager/src/GenerateDevice/LoadInfoThread.cpp
启动时重新刷新设备信息
Log: 设备网络信息显示
/review @lzwind @jeffshuai @feeengli @hundundadi @myk1343 @pengfeixx
> fix: 设备网络信息显示不全

- deepin-devicemanager/src/DeviceManager/DeviceGpu.cpp
移除HW显卡最大最小分辨率
Log: 移除HW显卡最大最小分辨率
/review @lzwind @jeffshuai @feeengli @myk1343 @pengfeixx @hundundadi
> fix: HW显卡最大最小分辨率错误

- deepin-devicemanager-server/src/DriverControl/DriverDBusInterface.cpp
添加检查驱动接口限制
Log: 添加检查驱动接口限制
/review @lzwind @jeffshuai @feeengli @pengfeixx @HeeMingYang @myk1343
> fix: 检查驱动接口存在安全漏洞

- deepin-devicemanager-server/src/LoadInfo/cpu/CpuInfo.cpp
统一去掉非数组分割标识
Log: 正确显示CPU核心数
/review @lzwind @pengfeixx @jeffshuai @feeengli @hundundadi @myk1343
> fix: 修改CPU核分割不统一问题

- deepin-devicemanager-server/src/LoadInfo/cpu/CoreCpu.cpp
- deepin-devicemanager-server/src/LoadInfo/cpu/CoreCpu.h
- deepin-devicemanager-server/src/LoadInfo/cpu/CpuInfo.cpp
- deepin-devicemanager-server/src/LoadInfo/cpu/PhysicalCpu.cpp
- deepin-devicemanager-server/src/LoadInfo/cpu/PhysicalCpu.h
使用第一个ID作为核心ID
Log: 正常显示核心ID
/review @lzwind @jeffshuai @feeengli @pengfeixx @hundundadi @myk1343
> fix: 修改了cpu核芯ID错误

- deepin-devicemanager-server/src/LoadInfo/cpu/CpuInfo.cpp
通过线程ID赋值
Log: 正确显示core里查找到线程导致信息
> fix: 修改了未在core里查找到线程导致信息不全

- deepin-devicemanager/src/DeviceManager/DeviceNetwork.cpp
通过lsusb获取USB外接网络适配器
Log: 正确显示USB外接网络适配器的制造商
Bug: https://pms.uniontech.com/bug-view-162141.html
/review @pengfeixx @jeffshuai @myk1343 @feeengli @HeeMingYang
> fix: USB外接网络适配器的制造商无法获取

- CMakeLists.txt
- deepin-devicemanager-server/CMakeLists.txt
- deepin-devicemanager/CMakeLists.txt
log: use GNUInstallDirs in CmakeLists
https://github.com/linuxdeepin/developer-center/issues/3167
> chore: use GNUInstallDirs in CmakeLists

- deepin-devicemanager/src/Widget/GetDriverNameWidget.cpp
隐藏提示标签
Log: 更新驱动弹窗居中提示词
Bug: https://pms.uniontech.com/bug-view-157703.html
/review @lzwind @pengfeixx @jeffshuai @feeengli @myk1343 @HeeMingYang
> fix: 更新驱动弹窗提示词不居中

- deepin-devicemanager/src/Widget/RichTextDelegate.cpp
增加列表底部高度
Log: 正常显示列表内容较多的间距
Bug: https://pms.uniontech.com/bug-view-157701.html
/review @lzwind @jeffshuai @feeengli @pengfeixx
> fix: 列表内容较多时的间距问题

- deepin-devicemanager-server/src/LoadInfo/ThreadPool.cpp
- deepin-devicemanager/src/Page/MainWindow.cpp
> fix: 设备管理器社区版本coredump

- debian/control
- deepin-devicemanager/src/GenerateDevice/DeviceGenerator.cpp
> fix: 签名工具非必需

- deepin-devicemanager/src/Page/DeviceWidget.cpp
- deepin-devicemanager/src/Page/DeviceWidget.h
- deepin-devicemanager/src/Page/MainWindow.cpp
- deepin-devicemanager/src/Page/PageDetail.cpp
- deepin-devicemanager/src/Page/PageDriverManager.cpp
- deepin-devicemanager/src/Page/PageInfoWidget.cpp
- deepin-devicemanager/src/Page/PageInfoWidget.h
- deepin-devicemanager/src/Page/PageListView.cpp
- deepin-devicemanager/src/Page/PageListView.h
- deepin-devicemanager/src/Page/PageOverview.cpp
刷新数据时先将界面数据清除
Log: 正确刷新界面
Bug: https://pms.uniontech.com/bug-view-162167.html
> fix: 右键刷新后切换界面概率性闪退

- deepin-devicemanager/src/environments.h.in
> fix: 开源合规修改

- deepin-devicemanager/src/Page/MainWindow.cpp
- deepin-devicemanager/src/Page/PageDriverManager.cpp
- deepin-devicemanager/src/Page/PageDriverManager.h
扫描驱动时禁止刷新设备
Log: 正常切换设备信息
Bug: https://pms.uniontech.com/bug-view-162167.html
> fix: 切换驱动界面后再设备界面右键刷新后切换界面概率性闪退

- deepin-devicemanager/src/Page/MainWindow.cpp
- deepin-devicemanager/src/Page/PageSingleInfo.cpp
> fix: 连续按F5和鼠标右键coredump

- deepin-devicemanager-server/src/EnableControl/EnableUtils.cpp
- deepin-devicemanager-server/src/HotPlug/DetectThread.cpp
- deepin-devicemanager-server/src/WakeControl/WakeupUtils.cpp
- deepin-devicemanager/src/DeviceManager/DeviceInfo.cpp
- deepin-devicemanager/src/GenerateDevice/CmdTool.cpp
- deepin-devicemanager/src/GenerateDevice/DeviceGenerator.cpp
重新计算Unique ID作为key值
Log: 正常禁用设备
Bug: https://pms.uniontech.com/bug-view-164801.html
> fix: 鼠标详情页面右键禁用且重新拔插鼠标之后鼠标能正常使用

- deepin-devicemanager-server/src/HotPlug/DetectThread.cpp
- deepin-devicemanager-server/src/WakeControl/WakeupUtils.cpp
- deepin-devicemanager/src/GenerateDevice/CmdTool.cpp
计算UniqueID调整
Log: 计算UniqueID调整
> fix: 计算UniqueID调整

- deepin-devicemanager/src/GenerateDevice/HWGenerator.cpp
- deepin-devicemanager/src/GenerateDevice/KLUGenerator.cpp
- deepin-devicemanager/src/GenerateDevice/KLVGenerator.cpp
增加读取UFS 3.1信息
Log: 正确显示UFS 3.1信息
Task: https://pms.uniontech.com/task-view-219097.html
> feat: 读取设备管理器UFS 3.1

- deepin-devicemanager/src/SingleDeviceManager.cpp
修改窗口显示状态
Log: 正常显示窗口
Bug: https://pms.uniontech.com/bug-view-175147.html
> fix: 非特效模式设备管理器最小化状态下启动器点击打开设备管理器后未正常显示

- deepin-devicemanager/src/GenerateDevice/HWGenerator.cpp
- deepin-devicemanager/src/GenerateDevice/KLVGenerator.cpp
> fix: 移除部分磁盘类型判断

- deepin-devicemanager-server/CMakeLists.txt
- deepin-devicemanager/CMakeLists.txt
- deepin-devicemanager/src/Page/MainWindow.cpp
> fix: 取消驱动相关界面

- deepin-devicemanager/src/GenerateDevice/CmdTool.cpp
内存信息dmidecode无法查到时增加显示内存大小
Log: 正常显示内存大小
> fix: 无内存信息

- deepin-devicemanager-server/CMakeLists.txt
- deepin-devicemanager/CMakeLists.txt
- deepin-devicemanager/src/GenerateDevice/DeviceFactory.cpp
- deepin-devicemanager/src/GenerateDevice/KLUGenerator.cpp
- deepin-devicemanager/src/GenerateDevice/KLUGenerator.h
> fix: 添加机型判断

- deepin-devicemanager/src/GenerateDevice/KLVGenerator.cpp
> fix: 调整磁盘接口类型

- .tx/deepin.conf
- debian/changelog
> chore: 更新版本5.9.5

- deepin-devicemanager/src/GenerateDevice/DeviceGenerator.cpp
增加未分类的usb的蓝牙设备判断
Log: 正确显示蓝牙设备
> fix: 无法读取未分类的usb的蓝牙设备

- deepin-devicemanager/src/EnableControl/DBusTouchPad.cpp
- deepin-devicemanager/src/Tool/ThreadExecXrandr.cpp
- deepin-devicemanager/src/Widget/DetectedStatusWidget.cpp
- deepin-devicemanager/src/main.cpp
> fix: 调整dbus接口

- deepin-devicemanager/src/commonfunction.cpp
> fix: 更新类型判断

- deepin-devicemanager/src/DeviceManager/DeviceBluetooth.cpp
- deepin-devicemanager/src/DeviceManager/DeviceImage.cpp
- deepin-devicemanager/src/DeviceManager/DeviceInput.cpp
- deepin-devicemanager/src/DeviceManager/DeviceOthers.cpp
> fix: 设备序列号乱码

- deepin-devicemanager/assets/oeminfo_sampleAnduseGuideLine.toml
- deepin-devicemanager/assets/oeminfo_sampleAnduseGuideLine_zh_CN.toml
- deepin-devicemanager/src/GenerateDevice/CmdTool.cpp
add the userGuideLine for toml solution
Log: add the userGuideLine for toml solution
> feat: add the userGuideLine for toml solution

- deepin-devicemanager/src/EnableControl/DBusTouchPad.cpp
更新touchpad的dbus
Log: 正常操作touchpad
> fix: 更新touchpad的dbus

- deepin-devicemanager/src/DeviceManager/DeviceStorage.cpp
- deepin-devicemanager/src/GenerateDevice/DeviceGenerator.cpp
> fix: 添加U盘设备识别

- debian/control
- deepin-devicemanager-server/CMakeLists.txt
- deepin-devicemanager-server/tests/CMakeLists.txt
- deepin-devicemanager/CMakeLists.txt
- deepin-devicemanager/src/DeviceManager/DeviceInput.cpp
- deepin-devicemanager/src/EnableControl/DBusTouchPad.cpp
- deepin-devicemanager/src/EnableControl/DBusTouchPad.h
- deepin-devicemanager/tests/CMakeLists.txt
> fix: 使用新的dbus接口

- deepin-devicemanager/src/Page/PageSingleInfo.cpp
- deepin-devicemanager/src/Page/PageTableWidget.cpp
多行数据影响单行数据显示
Log: 信息一致显示
Bug: https://pms.uniontech.com/bug-view-184353.html
> fix: 设备管理器中有些字段字体加粗与其他信息显示不一致

- deepin-devicemanager/src/GenerateDevice/HWGenerator.cpp
> fix: gpu名称错误

- debian/changelog
> chore: 更新版本5.9.6

- debian/changelog
- deepin-devicemanager/src/GenerateDevice/DBusInterface.cpp
> fix: 修改tag类型

- debian/changelog
- deepin-devicemanager/src/GenerateDevice/DBusInterface.cpp
> fix: 更新版本5.9.7

- deepin-devicemanager/src/Widget/DetailTreeView.cpp
> fix: 修改了鼠标事件问题

- debian/changelog
> chore: 更新版本5.9.8

- deepin-devicemanager/src/GenerateDevice/HWGenerator.cpp
去除不正确的过滤方式
Log: 正确显示网络模块
Bug: https://pms.uniontech.com/bug-view-187583.html,https://pms.uniontech.com/bug-view-187585.html
> fix: 无网络适配器模块

- deepin-devicemanager-server/src/EnableControl/EnableSqlManager.cpp
- deepin-devicemanager-server/src/EnableControl/EnableSqlManager.h
- deepin-devicemanager-server/src/HotPlug/DetectThread.cpp
- deepin-devicemanager-server/src/HotPlug/DetectThread.h
- deepin-devicemanager-server/src/HotPlug/MonitorUsb.cpp
- deepin-devicemanager-server/src/HotPlug/MonitorUsb.h
- deepin-devicemanager-server/src/LoadInfo/DBusInterface.cpp
- deepin-devicemanager-server/src/LoadInfo/DBusInterface.h
- deepin-devicemanager-server/src/MainJob.cpp
- deepin-devicemanager-server/src/MainJob.h
- deepin-devicemanager/src/DeviceManager/DeviceInput.cpp
> feat: 增加了监控设备状态接口

- deepin-devicemanager/src/GenerateDevice/DeviceFactory.cpp
- deepin-devicemanager/src/GenerateDevice/LoadInfoThread.cpp
增加读取显示器信息方法
Log: 正确显示显示器
Bug: https://pms.uniontech.com/bug-view-186287.html
> fix: 部分机型没有显示设备项

- debian/changelog
> chore: 更新版本5.9.9

- deepin-devicemanager/translations/deepin-devicemanager.ts
- deepin-devicemanager/translations/deepin-devicemanager_zh_CN.ts
> chore: 增加中文翻译

- deepin-devicemanager-server/src/LoadInfo/ThreadPool.cpp
- deepin-devicemanager/src/DeviceManager/DeviceMonitor.cpp
- deepin-devicemanager/src/GenerateDevice/CmdTool.cpp
增加hwinfo的framebuffer类型显示器
Log: 正常显示显示器
> fix: 修改了部分机子显示器不显示

- debian/changelog
> chore: 更新版本5.9.10

- deepin-devicemanager-server/src/LoadInfo/ThreadPool.cpp
- deepin-devicemanager/src/DeviceManager/DeviceMonitor.cpp
- deepin-devicemanager/src/GenerateDevice/CmdTool.cpp
- deepin-devicemanager/translations/deepin-devicemanager.ts
- deepin-devicemanager/translations/deepin-devicemanager_zh_CN.ts
增加hwinfo的framebuffer类型显示器、隐藏显示器的生产日期和更新电池第一个容量为最大容量
Log: 正常显示显示器和更新电池第一个容量为最大容量
> fix: 修改了部分机子显示器不显示和去掉显示器的生产日期并更新电池容量

- debian/changelog
> chore: 更新版本5.9.11

- debian/changelog
> chore: 更新版本6.0.6

- .reuse/dep5
- CMakeLists.txt
- deepin-devicemanager-server/CMakeLists.txt
- deepin-devicemanager-server/src/DriverControl/DebInstaller.cpp
- deepin-devicemanager-server/src/DriverControl/DebInstaller.h
- deepin-devicemanager-server/src/DriverControl/DriverDBusInterface.cpp
- deepin-devicemanager-server/src/DriverControl/DriverDBusInterface.h
- deepin-devicemanager-server/src/DriverControl/DriverInstaller.cpp
- deepin-devicemanager-server/src/DriverControl/DriverInstaller.h
- deepin-devicemanager-server/src/DriverControl/DriverManager.cpp
- deepin-devicemanager-server/src/DriverControl/DriverManager.h
- deepin-devicemanager-server/src/DriverControl/ModCore.cpp
- deepin-devicemanager-server/src/DriverControl/ModCore.h
- deepin-devicemanager-server/src/MainJob.cpp
- deepin-devicemanager-server/src/main.cpp
- deepin-devicemanager/CMakeLists.txt
- deepin-devicemanager/src/DriverControl/DBusDriverInterface.cpp
- deepin-devicemanager/src/Page/MainWindow.cpp
- rpm/deepin-devicemanager.spec
> feat: 添加驱动模块宏

- .reuse/dep5
- CMakeLists.txt
- deepin-devicemanager-server/deepin-devicecontrol/CMakeLists.txt
- deepin-devicemanager-server/deepin-devicecontrol/src/controlinterface.cpp
- deepin-devicemanager-server/deepin-devicecontrol/src/controlinterface.h
- deepin-devicemanager-server/deepin-devicecontrol/src/drivercontrol/debinstaller.cpp
- deepin-devicemanager-server/deepin-devicecontrol/src/drivercontrol/debinstaller.h
- deepin-devicemanager-server/deepin-devicecontrol/src/drivercontrol/driverinstaller.cpp
- deepin-devicemanager-server/deepin-devicecontrol/src/drivercontrol/driverinstaller.h
- deepin-devicemanager-server/deepin-devicecontrol/src/drivercontrol/drivermanager.cpp
- deepin-devicemanager-server/deepin-devicecontrol/src/drivercontrol/drivermanager.h
- deepin-devicemanager-server/deepin-devicecontrol/src/drivercontrol/modcore.cpp
- deepin-devicemanager-server/deepin-devicecontrol/src/drivercontrol/modcore.h
- deepin-devicemanager-server/deepin-deviceinfo/CMakeLists.txt
- deepin-devicemanager/CMakeLists.txt
- deepin-devicemanager/src/DriverControl/DBusDriverInterface.cpp
- deepin-devicemanager/src/Page/MainWindow.cpp
- rpm/deepin-devicemanager.spec
> feat: 添加驱动模块判断宏

- deepin-devicemanager-server/src/MainJob.cpp
> fix: 无驱动模块时去掉驱动源

- debian/changelog
> chore: 更新版本5.9.12

- deepin-devicemanager/src/GenerateDevice/KLUGenerator.cpp
- deepin-devicemanager/src/GenerateDevice/KLUGenerator.h
设备管理器 概况-网络适配中klu缺少无线的展示 Hi1103
Log: 设备管理器 概况-网络适配中klu缺少无线的展示 Hi1103
Bug: https://pms.uniontech.com/bug-view-197543.html
> fix: 设备管理器 概况-网络适配中klu缺少无线的展示 Hi1103

- debian/changelog
> chore: 更新版本5.9.13

- deepin-devicemanager/src/DeviceManager/DeviceNetwork.cpp
- deepin-devicemanager/src/GenerateDevice/PanguVGenerator.cpp
- deepin-devicemanager/src/GenerateDevice/PanguVGenerator.h
设备管理器-PAGUW网络适配器信息不显示无线网卡信息
Log: 设备管理器-PAGUW网络适配器信息不显示无线网卡信息
Bug: https://pms.uniontech.com/bug-view-198293.html
> fix: 设备管理器-PAGUW网络适配器信息不显示无线网卡信息

- deepin-devicemanager/src/commonfunction.cpp
设备管理器M900-1050-update3-arm64-20230216-1644无GPU信息
Log: 设备管理器M900-1050-update3-arm64-20230216-1644无GPU信息
Bug: https://pms.uniontech.com/bug-view-187791.html
> fix: 设备管理器M900-1050-update3-arm64-20230216-1644无GPU信息

- debian/changelog
> chore: 更新版本5.9.14

- deepin-devicemanager/src/commonfunction.cpp
Description: 增加hw W585新机型判断
Log: 增加hw W585新机型判断
> chore: 增加hw W585新机型判断

- deepin-devicemanager/src/DeviceManager/DeviceNetwork.cpp
- deepin-devicemanager/src/GenerateDevice/KLUGenerator.cpp
- deepin-devicemanager/src/GenerateDevice/KLUGenerator.h
- deepin-devicemanager/src/GenerateDevice/PanguVGenerator.cpp
- deepin-devicemanager/src/GenerateDevice/PanguVGenerator.h
- deepin-devicemanager/src/commonfunction.cpp
增加hw W585新机型判断
设备管理器M900-1050-update3-arm64-20230216-1644无GPU信息
设备管理器-PAGUW网络适配器信息不显示无线网卡信息
设备管理器 概况-网络适配中klu缺少无线的展示 Hi1103-2addKLVU
Bug: https://pms.uniontech.com/bug-view-187791.html
Bug: https://pms.uniontech.com/bug-view-198293.html
Bug: https://pms.uniontech.com/bug-view-197543.html
> chore: sync with 105x

- debian/changelog
update version 6.0.7
Log: update version 6.0.7
> chore: update version 6.0.7

- deepin-devicemanager/src/DeviceManager/DeviceNetwork.cpp
- deepin-devicemanager/src/commonfunction.cpp
设备管理器华为W585适配net
Log:  设备管理器华为W585适配net
Task: https://pms.uniontech.com/task-view-264947.html
> feat: 设备管理器华为W585适配net

- debian/changelog
> chore: 更新版本5.9.15

- debian/changelog
- deepin-devicemanager/src/GenerateDevice/LoadInfoThread.cpp
cover the shutdown and exit may fail sometimes
Log: cover the shutdown and exit may fail sometimes
Bug: https://pms.uniontech.com/bug-view-200233.html
> fix: cover the shutdown and exit may fail sometimes

- debian/changelog
update version 5.9.17
Log: update version 5.9.17
> chore: update version 5.9.17

- deepin-devicemanager/src/GenerateDevice/KLUGenerator.cpp
- deepin-devicemanager/src/GenerateDevice/KLUGenerator.h
修复1060设备管理器无显示设备信息
Log: 修复1060设备管理器无显示设备信息
> fix: 修复1060设备管理器无显示设备信息

- debian/changelog
update version 6.0.8
Log: update version 6.0.8
> chore: update version 6.0.8

- debian/control
修复1060设备管理器后端末启动无信息显示
Log: 修复1060设备管理器后端末启动无信息显示
> fix: 修复1060设备管理器后端末启动无信息显示

- deepin-devicemanager/src/DeviceManager/DeviceManager.cpp
- deepin-devicemanager/src/DeviceManager/DeviceManager.h
- deepin-devicemanager/src/DeviceManager/DeviceMonitor.cpp
- deepin-devicemanager/src/DeviceManager/DeviceMonitor.h
- deepin-devicemanager/src/GenerateDevice/PanguVGenerator.cpp
- deepin-devicemanager/src/Tool/ThreadExecXrandr.cpp
- deepin-devicemanager/src/Tool/ThreadExecXrandr.h
修复部分显示设备中当前分辨率信息与实际设置的不符
Log: 修复部分显示设备中当前分辨率信息与实际设置的不符
Bug: https://pms.uniontech.com/bug-view-204349.html
> fix: 修复部分显示设备中当前分辨率信息与实际设置的不符

- .tx/config
> chore: 更新翻译配置

- deepin-devicemanager/src/DeviceManager/DeviceMonitor.cpp
> fix: 修复当前分辨率未显示

- deepin-devicemanager/CMakeLists.txt
- deepin-devicemanager/assets/org.deepin.devicemanager.json
- deepin-devicemanager/src/Page/MainWindow.cpp
- deepin-devicemanager/src/commonfunction.cpp
- deepin-devicemanager/src/commonfunction.h
Description: hw机型判断适配dconfig
Log: hw机型判断适配dconfig
Task: https://pms.uniontech.com/task-view-276433.html
> feat: hw机型判断适配dconfig

- deepin-devicemanager/src/DeviceManager/DeviceGpu.cpp
优化部分显示设备中Name与Model
Log:优化部分显示设备中Name与Model
> fix: 优化部分显示设备中Name与Model

- debian/changelog
update version  6.0.10
Log: update version  6.0.10
> chore: update version 6.0.10

- debian/changelog
bump version  5.9.18
Log: bump version  5.9.18
> chore: bump version 5.9.18

- deepin-devicemanager/src/DeviceManager/DeviceStorage.cpp
修复某些型号U盘不认识
Log: 修复某些型号U盘不认识
Bug: https://pms.uniontech.com/bug-view-211371.html
> fix: 修复某些型号U盘不认识

- deepin-devicemanager/translations/deepin-devicemanager_zh_CN.ts
修改BogoMIPS中文显示为【运行速度（Bogomips）】
Log: 修改BogoMIPS中文显示为【运行速度（Bogomips）】
Bug: https://pms.uniontech.com/bug-view-206663.html
> fix: 修改BogoMIPS中文显示

- debian/changelog
- debian/deepin-devicemanager.postinst
- deepin-devicemanager-server/deepin-deviceinfo/CMakeLists.txt
- deepin-devicemanager-server/deepin-deviceinfo/src/mainjob.cpp
移除devicemanager.list,该软件源与打印管理器源重复
Log:
> feat: Community Edition removal devicemanager.list 

- deepin-devicemanager/src/DeviceManager/DeviceStorage.cpp
merge disk size unit error
Log:  merge disk size unit error
Bug: https://pms.uniontech.com/bug-view-211013.html
> fix: merge disk size unit error

- CMakeLists.txt
- deepin-devicemanager-server/deepin-devicecontrol/src/controlinterface.cpp
- deepin-devicemanager-server/deepin-devicecontrol/src/controlinterface.h
- deepin-devicemanager-server/deepin-devicecontrol/src/drivercontrol/drivermanager.cpp
- deepin-devicemanager-server/deepin-devicecontrol/src/drivercontrol/drivermanager.h
- deepin-devicemanager/assets/com.deepin.deepin-devicemanager.policy
设备管理器驱动备份还原service端功能
Log: 设备管理器驱动备份还原service
Task: https://pms.uniontech.com/task-view-285255.html
> feat: 设备管理器驱动备份还原service端功能

- deepin-devicemanager/src/DriverControl/DBusDriverInterface.cpp
- deepin-devicemanager/src/Page/PageDriverRestoreInfo.cpp
修复备份还原时进度未刷新问题
Log: 修复备份还原时进度未刷新问题
> fix: 备份还原时进度未刷新

- deepin-devicemanager/src/DeviceManager/DeviceMonitor.cpp
- deepin-devicemanager/src/DeviceManager/DeviceMonitor.h
make tomel  static no update
Log:  make tomel  static no update
> feat: make tomel  static no update

- deepin-devicemanager-server/deepin-devicecontrol/src/wakecontrol/ethtool-copy.h
- deepin-devicemanager-server/deepin-devicecontrol/src/wakecontrol/wakeuputils.cpp
- deepin-devicemanager/src/DeviceManager/DeviceMonitor.cpp
- deepin-devicemanager/src/DeviceManager/DeviceMonitor.h
同步ethtool功能到设备管理器中“允许唤起电脑”
Log: 同步ethtool功能到设备管理器中“允许唤起电脑”
Bug: https://pms.uniontech.com/bug-view-220657.html
> fix: 同步ethtool功能到设备管理器中“允许唤起电脑”

- deepin-devicemanager/src/Page/PageSingleInfo.cpp
- deepin-devicemanager/src/Widget/DetectedStatusWidget.cpp
- deepin-devicemanager/src/Widget/UrlChooserEdit.cpp
cover  CRP fail for eagle-sp2
Log: cover  CRP fail for eagle-sp2
> fix: cover  CRP fail for eagle-sp2

- deepin-devicemanager/src/DeviceManager/DeviceInfo.cpp
- deepin-devicemanager/src/DriverControl/HttpDriverInterface.cpp
- deepin-devicemanager/src/MacroDefinition.h
- deepin-devicemanager/src/Page/PageDriverBackupInfo.cpp
- deepin-devicemanager/src/Page/PageDriverManager.cpp
- deepin-devicemanager/src/Tool/commontools.cpp
驱动管理增加其它驱动的扫描与备份
Log: 驱动管理增加其它驱动的扫描与备份
> fix: 驱动管理增加其它驱动的扫描与备份

- deepin-devicemanager/src/Widget/drivertableview.cpp
修复一键备份时状态不刷问题
Log: 修复一键备份状态不刷新问题
> fix: 一键备份状态不刷新

- deepin-devicemanager/src/Page/PageDriverBackupInfo.cpp
- deepin-devicemanager/src/Page/PageDriverBackupInfo.h
- deepin-devicemanager/src/Page/PageDriverManager.cpp
- deepin-devicemanager/src/Page/PageDriverRestoreInfo.cpp
- deepin-devicemanager/src/Page/PageDriverRestoreInfo.h
- deepin-devicemanager/src/Page/PageDriverTableView.cpp
- deepin-devicemanager/src/Page/PageDriverTableView.h
- deepin-devicemanager/src/Widget/DetectedStatusWidget.cpp
- deepin-devicemanager/src/Widget/DetectedStatusWidget.h
- deepin-devicemanager/src/Widget/drivertableview.cpp
修复备份还原过程中状态、信息未及时刷新问题
Log: 修复备份还原过程中状态、信息未及时刷新问题
Bug: https://pms.uniontech.com/bug-view-226295.html
https://pms.uniontech.com/bug-view-226323.html
https://pms.uniontech.com/bug-view-226377.html
> fix: 修复备份还原过程中状态、信息未及时刷新问题

- deepin-devicemanager-server/deepin-devicecontrol/src/wakecontrol/ethtool-copy.h
- deepin-devicemanager-server/deepin-devicecontrol/src/wakecontrol/wakeuputils.cpp
- deepin-devicemanager/src/DeviceManager/DeviceMonitor.cpp
- deepin-devicemanager/src/DeviceManager/DeviceMonitor.h
- deepin-devicemanager/src/DeviceManager/DeviceStorage.cpp
- deepin-devicemanager/src/Page/PageSingleInfo.cpp
- deepin-devicemanager/src/Widget/DetectedStatusWidget.cpp
- deepin-devicemanager/src/Widget/UrlChooserEdit.cpp
cheery pick to master somefixup
Log: cheery pick to master somefixup
> chore: cheery pick 105x nobanup to master somefix

- deepin-devicemanager/src/DeviceManager/DeviceInfo.cpp
- deepin-devicemanager/src/DeviceManager/DeviceNetwork.cpp
- deepin-devicemanager/src/GenerateDevice/DeviceGenerator.cpp
en01与en02网口MAC相同导致信息识别不全
Log: 网口的信息识别全
Bug: https://pms.uniontech.com/bug-view-230087.html
> fix: 修复部分网址设备识别问题

- debian/changelog
- deepin-devicemanager/src/DeviceManager/DeviceInfo.cpp
- deepin-devicemanager/src/DeviceManager/DeviceNetwork.cpp
- deepin-devicemanager/src/GenerateDevice/DeviceGenerator.cpp
> chore: bump version 5.9.20 

- deepin-devicemanager/src/GenerateDevice/HWGenerator.cpp
部分机型storage设备识别不到制造商
Log: 修复部分storage设备识别问题
Bug: https://pms.uniontech.com/bug-view-232899.html
> fix: 修复部分机型storage设备识别问题

- deepin-devicemanager-server/src/LoadInfo/ThreadPool.cpp
- deepin-devicemanager/src/DeviceManager/DeviceMonitor.cpp
- deepin-devicemanager/src/DeviceManager/DeviceNetwork.cpp
- deepin-devicemanager/src/GenerateDevice/DeviceFactory.cpp
- deepin-devicemanager/src/GenerateDevice/DeviceGenerator.cpp
- deepin-devicemanager/src/GenerateDevice/HWGenerator.cpp
- deepin-devicemanager/src/GenerateDevice/M900Generator.cpp
- deepin-devicemanager/src/GenerateDevice/M900Generator.h
- deepin-devicemanager/src/Tool/EDIDParser.cpp
- deepin-devicemanager/src/Tool/EDIDParser.h
- deepin-devicemanager/src/Tool/commontools.cpp
- deepin-devicemanager/src/Tool/commontools.h
- deepin-devicemanager/src/commonfunction.cpp
M900问题修复
Log: M900问题修复
Bug: https://pms.uniontech.com/bug-view-221883.html
Bug: https://pms.uniontech.com/bug-view-187791.html
Bug: https://pms.uniontech.com/bug-view-207245.html
Bug: https://pms.uniontech.com/bug-view-207187.html
> fix: M900问题修复

- deepin-devicemanager-server/deepin-devicecontrol/src/wakecontrol/wakeuputils.cpp
修复DeviceControl缓冲区溢出漏洞
Log: 修复DeviceControl缓冲区溢出漏洞
Bug: https://pms.uniontech.com/bug-view-233127.html
> fix: 修复DeviceControl缓冲区溢出漏洞

- debian/changelog
> chore: bump version 6.0.16

- deepin-devicemanager/src/Page/MainWindow.cpp
修复热拔插识别显示设备
Log: 修复热拔插识别显示设备
Bug: https://pms.uniontech.com/bug-view-234593.html
> fix: 修复热拔插识别显示设备

- debian/changelog
> chore: bump version 6.0.18

- debian/changelog
> chore: bump version 6.0.19

- deepin-devicemanager/assets/org.deepin.devicemanager.json
- deepin-devicemanager/src/DeviceManager/DeviceBluetooth.cpp
- deepin-devicemanager/src/GenerateDevice/DeviceFactory.cpp
- deepin-devicemanager/src/GenerateDevice/PanguxGenerator.cpp
- deepin-devicemanager/src/GenerateDevice/PanguxGenerator.h
- deepin-devicemanager/src/commonfunction.cpp
- deepin-devicemanager/src/commonfunction.h
add PanguX for deepin-devicemanager
Log:  add PanguX for deepin-devicemanager
> feat: add PanguX for deepin-devicemanager

- debian/changelog
> chore: bump version 6.0.20

- debian/changelog
> chore: tag 6.0.21

- deepin-devicemanager/src/DeviceManager/DeviceMemory.cpp
为某机型内存最大频率修改成配置频率
Log:  某为机型内存最大频率修改成配置频率
Bug: https://pms.uniontech.com/bug-view-242993.html
> fix: 为某机型内存最大频率修改成配置频率

- deepin-devicemanager/src/GenerateDevice/PanguxGenerator.cpp
- deepin-devicemanager/src/GenerateDevice/PanguxGenerator.h
为某机定制CPU名字显示
Log:  某为定制CPU名字显示
Bug: https://pms.uniontech.com/bug-view-244199.html
> fix: 某为定制CPU名字显示

- debian/changelog
> chore: bump version 6.0.22

- deepin-devicemanager/src/GenerateDevice/LoadInfoThread.cpp
- deepin-devicemanager/src/Page/MainWindow.cpp
- deepin-devicemanager/src/Tool/ThreadExecXrandr.cpp
- deepin-devicemanager/src/Tool/ThreadExecXrandr.h
优化设备管理器偶现点击左侧菜单栏界面无响应
Log:  优化设备管理器偶现点击左侧菜单栏界面无响应
Bug: https://pms.uniontech.com/bug-view-228913.html
> fix: 优化设备管理器偶现点击左侧菜单栏界面无响应

- deepin-devicemanager-server/deepin-devicecontrol/src/drivercontrol/httpdriverinterface.cpp
- deepin-devicemanager/src/DriverControl/HttpDriverInterface.cpp
修复某声卡驱动解析问题
Log:  修复某声卡驱动解析问题和日志输出优化
Bug: https://pms.uniontech.com/bug-view-248239.html
> fix: 修复某声卡驱动解析问题

- debian/changelog
update version to 6.0.24
Log: update version to 6.0.24
Bug: no
> feat: update version to 6.0.24

- deepin-devicemanager/src/GenerateDevice/LoadInfoThread.cpp
- deepin-devicemanager/src/GenerateDevice/LoadInfoThread.h
- deepin-devicemanager/src/Page/MainWindow.cpp
- deepin-devicemanager/src/Page/MainWindow.h
调用DApplication setOverrideCursor窗口偶现闪退
Log:  修复窗口偶现闪退
Bug: https://pms.uniontech.com/bug-view-251039.html
> fix: 修复窗口偶现闪退

- debian/changelog
> chore: bump version 6.0.26

- deepin-devicemanager/src/GenerateDevice/CmdTool.cpp
过滤重复网卡逻辑名称数据
Log: 修改识别网卡的逻辑名称错误
Bug: https://pms.uniontech.com/bug-view-253311.html
> fix: 识别网卡的逻辑名称错误

- deepin-devicemanager/src/DeviceManager/DeviceManager.cpp
- deepin-devicemanager/src/DeviceManager/DeviceStorage.cpp
Fix the issue of errors in the hard disk capacity of certain specific models
Log: Fix the issue of errors in the hard disk capacity of certain specific models
Bug: https://pms.uniontech.com/bug-view-251377.html
> fix: Fix the issue of errors in the hard disk capacity of certain specific models

- deepin-devicemanager/src/DeviceManager/DeviceMemory.cpp
Configgured Speed显示英文
Log:  Configgured Speed显示中文
Bug: https://pms.uniontech.com/bug-view-252641.html
> fix:  修改Configgured Speed显示中文翻译

- deepin-devicemanager/src/DeviceManager/DeviceImage.cpp
显示camera不可用
Log:  修改显示可用
Bug: https://pms.uniontech.com/bug-view-255489.html
> fix:  camera显示不可用

- deepin-devicemanager/src/DeviceManager/DeviceStorage.cpp
部分UFS设备接口信息显示为UFS
Log:  部分UFS设备接口信息显示为UFS
Bug: https://pms.uniontech.com/bug-view-251373.html
> fix:  部分UFS设备接口信息显示为UFS

- deepin-devicemanager/src/DeviceManager/DeviceManager.cpp
- deepin-devicemanager/src/DeviceManager/DeviceStorage.cpp
- deepin-devicemanager/src/DeviceManager/DeviceStorage.h
部分disk容量信息255GB 511GB 1.5TB
Log: 修正部分disk容量信息为正确值
Bug: https://pms.uniontech.com/bug-view-251369.html
> fix:  修正部分disk容量信息

- deepin-devicemanager/src/DeviceManager/DeviceMonitor.cpp
- deepin-devicemanager/src/GenerateDevice/HWGenerator.cpp
- deepin-devicemanager/src/GenerateDevice/HWGenerator.h
- deepin-devicemanager/src/Tool/EDIDParser.cpp
- deepin-devicemanager/src/Tool/EDIDParser.h
解析显示设备模块
Log: 解析显示设备模块
Bug: https://pms.uniontech.com/bug-view-246695.html
> fix:  解析edid显示设备模块

- deepin-devicemanager/src/Page/PageDriverManager.cpp
修复卸载驱动时闪退
Log: 修复卸载驱动时闪退
Bug: https://pms.uniontech.com/bug-view-259851.html
> fix:  修复卸载驱动时闪退

- deepin-devicemanager/src/Page/PageMultiInfo.cpp
- deepin-devicemanager/src/Page/PageMultiInfo.h
修复快速切换左侧功能窗口闪退
Log: 修复快速切换左侧功能窗口闪退
Bug: https://pms.uniontech.com/bug-view-258247.html
> fix:  修复快速切换左侧功能窗口闪退

- debian/changelog
> chore: bump version 6.0.27

- deepin-devicemanager-server/deepin-devicecontrol/src/enablecontrol/enablesqlmanager.cpp
- deepin-devicemanager-server/deepin-devicecontrol/src/enablecontrol/enablesqlmanager.h
修复存在sql注入风险
Log: 修复存在sql注入风险
Bug: https://pms.uniontech.com/bug-view-264997.html
> fix:  修复存在sql注入风险

- deepin-devicemanager/src/GenerateDevice/DeviceGenerator.cpp
write 0 to file cpux/online , offline the cpux
Log:  修复没有计算offline cpu核
Bug: https://pms.uniontech.com/bug-view-264471.html
> fix: 修复没有计算offline cpu核

- deepin-devicemanager/src/DeviceManager/DeviceStorage.cpp
show Longsys vendor
Log:  show Longsys vendor
Bug: https://pms.uniontech.com/bug-view-265057.html
> fix:   show Longsys vendor

- deepin-devicemanager-server/deepin-deviceinfo/src/loadinfo/cpu/corecpu.cpp
- deepin-devicemanager-server/deepin-deviceinfo/src/loadinfo/cpu/cpuinfo.cpp
- deepin-devicemanager-server/deepin-deviceinfo/src/loadinfo/cpu/logicalcpu.cpp
- deepin-devicemanager-server/deepin-deviceinfo/src/loadinfo/cpu/logicalcpu.h
- deepin-devicemanager/src/DeviceManager/DeviceCpu.cpp
- deepin-devicemanager/src/DeviceManager/DeviceCpu.h
- deepin-devicemanager/translations/deepin-devicemanager_zh_CN.ts
D3000适配L4
Log: New cpu D3000适配
Task: https://pms.uniontech.com/task-view-358933.html
> feat:  显示cpu的L4缓存信息

- deepin-devicemanager/src/DeviceManager/DeviceCpu.cpp
调整为按序显示cpu的L4缓存信息
Log: 调整为按序显示cpu的L4缓存信息
Task: https://pms.uniontech.com/task-view-358933.html
> feat:  调整为按序显示cpu的L4缓存信息

- deepin-devicemanager/src/DeviceManager/DeviceStorage.cpp
Longsys  1.92T
Log:  Longsys  1.92T
Bug: https://pms.uniontech.com/bug-view-268779.html
> fix: for disk Longsys  1.92T

- deepin-devicemanager/src/DeviceManager/DeviceNetwork.cpp
- deepin-devicemanager/src/GenerateDevice/CmdTool.cpp
- deepin-devicemanager/src/GenerateDevice/DeviceGenerator.cpp
适配某机型CPU内集成网卡
Log: 适配某机型CPU内集成网卡
Task: https://pms.uniontech.com/task-view-359985.html
> feat: 适配某机型CPU内集成网卡

- deepin-devicemanager/src/DeviceManager/DeviceGpu.cpp
适配某独立显卡显存类型
Log: 适配某独立显卡显存类型
Task: https://pms.uniontech.com/task-view-360003.html
> feat: 适配某独立显卡显存类型

- deepin-devicemanager-server/deepin-devicecontrol/src/drivercontrol/drivermanager.cpp
- deepin-devicemanager-server/deepin-devicecontrol/src/drivercontrol/httpdriverinterface.cpp
- deepin-devicemanager-server/deepin-devicecontrol/src/drivercontrol/utils.cpp
- deepin-devicemanager-server/deepin-devicecontrol/src/drivercontrol/utils.h
命令注入漏洞安全
Log:  命令注入漏洞安全
Bug: https://pms.uniontech.com/bug-view-269973.html
> fix: 命令注入漏洞安全

- deepin-devicemanager-server/src/DriverControl/Utils.cpp
> fix: 命令注入漏洞安全qcInfo成qinfo

- debian/changelog
> chore: bump version 6.0.28

- deepin-devicemanager/src/DeviceManager/DeviceBluetooth.cpp
- deepin-devicemanager/src/DeviceManager/DeviceBluetooth.h
bluetooth  alias for sync dde
Log:  bluetooth add alias proper
Bug: https://pms.uniontech.com/bug-view-269257.html
> fix: bluetooth add alias proper

- deepin-devicemanager-server/deepin-devicecontrol/src/drivercontrol/driverinstaller.cpp
- deepin-devicemanager-server/deepin-devicecontrol/src/drivercontrol/drivermanager.cpp
- deepin-devicemanager-server/deepin-devicecontrol/src/drivercontrol/httpdriverinterface.cpp
- deepin-devicemanager-server/deepin-devicecontrol/src/drivercontrol/notifythread.cpp
- deepin-devicemanager-server/deepin-devicecontrol/src/drivercontrol/utils.cpp
- deepin-devicemanager-server/deepin-devicecontrol/src/drivercontrol/utils.h
- deepin-devicemanager-server/deepin-deviceinfo/src/loadinfo/threadpool.cpp
- deepin-devicemanager-server/deepin-deviceinfo/src/loadinfo/threadpooltask.cpp
- deepin-devicemanager-server/deepin-deviceinfo/src/loadinfo/threadpooltask.h
- deepin-devicemanager-server/deepin-deviceinfo/src/mainjob.cpp
- deepin-devicemanager/src/DDLog/DDLog.h
- deepin-devicemanager/src/DeviceManager/DeviceInfo.cpp
- deepin-devicemanager/src/DriverControl/DriverBackupThread.cpp
- deepin-devicemanager/src/DriverControl/DriverScanner.cpp
- deepin-devicemanager/src/DriverControl/HttpDriverInterface.cpp
- deepin-devicemanager/src/commonfunction.cpp
- deepin-devicemanager/src/commonfunction.h
- deepin-devicemanager/src/main.cpp
Remove bash calls and system script calls
Log: Remove bash calls and system script calls
Task: https://pms.uniontech.com/task-view-362323.html
> fix: [cmd] Remove bash calls and system script calls

- deepin-devicemanager-server/src/DriverControl/DriverDBusInterface.cpp
- deepin-devicemanager-server/src/DriverControl/DriverDBusInterface.h
- deepin-devicemanager-server/src/EnableControl/DBusEnableInterface.cpp
- deepin-devicemanager-server/src/EnableControl/DBusEnableInterface.h
as title
Log: add polkit support
> chore: [security] add polkit support

- deepin-devicemanager-server/deepin-deviceinfo/src/loadinfo/threadpooltask.cpp
- deepin-devicemanager/src/commonfunction.cpp
Add handling of the 'cat/boot/config*' command
Log: Add handling of the 'cat/boot/config*' command
Task: https://pms.uniontech.com/task-view-362323.html
> fix: [cmd] Add handling of the 'cat/boot/config*' command

- deepin-devicemanager-server/deepin-devicecontrol/src/controlinterface.cpp
add polkit support for root app
Log:  add polkit support for root app
Bug: https://pms.uniontech.com/bug-view-273929.html
> fix: add polkit support for root app

- deepin-devicemanager-server/deepin-deviceinfo/src/mainjob.cpp
- deepin-devicemanager-server/deepin-deviceinfo/src/mainjob.h
add S3 detect support
Log:  add S3 detect support
Bug: https://pms.uniontech.com/bug-view-273929.html
> fix: add S3 wakeup detect support

- deepin-devicemanager/src/DeviceManager/DeviceStorage.cpp
rounded ufs disk capacity
Log:  rounded ufs disk capacity
Bug: https://pms.uniontech.com/bug-view-276121.html
> fix:rounded ufs disk capacity

- deepin-devicemanager-server/deepin-devicecontrol/src/drivercontrol/drivermanager.cpp
- deepin-devicemanager-server/deepin-devicecontrol/src/drivercontrol/httpdriverinterface.cpp
- deepin-devicemanager-server/deepin-devicecontrol/src/drivercontrol/notifythread.cpp
- deepin-devicemanager-server/deepin-devicecontrol/src/drivercontrol/utils.cpp
- deepin-devicemanager-server/deepin-devicecontrol/src/drivercontrol/utils.h
- deepin-devicemanager-server/deepin-devicecontrol/src/enablecontrol/enableutils.cpp
- deepin-devicemanager-server/deepin-devicecontrol/src/enablecontrol/enableutils.h
- deepin-devicemanager/src/DeviceManager/DeviceInfo.cpp
- deepin-devicemanager/src/DriverControl/HttpDriverInterface.cpp
- deepin-devicemanager/src/commonfunction.cpp
- deepin-devicemanager/src/commonfunction.h
for dbus scan
Log:  strong the dbus interface
Task: https://pms.uniontech.com/task-view-365257.html
> chore: [security] strong the dbus interface

- deepin-devicemanager/src/DeviceManager/DeviceCpu.cpp
- deepin-devicemanager/translations/deepin-devicemanager_zh_CN.ts
某逻辑处理器的数量没有显示
Log: 某逻辑处理器的数量显示
Bug: https://pms.uniontech.com/bug-view-278565.html
> fix: 某逻辑处理器的数量显示

- debian/install
- debian/rules
- deepin-devicemanager-server/deepin-devicecontrol/CMakeLists.txt
- deepin-devicemanager-server/deepin-devicecontrol/deepin-service-group@.service.d/deepin-service-manager-override.conf
> chore: 解决由于安全加固，插件服务启动失败的问题

- deepin-devicemanager/src/GenerateDevice/KLVGenerator.cpp
support ext plugin monitor for some model
Log: support ext plugin monitor
Bug: https://pms.uniontech.com/bug-view-283735.html
> fix: support ext plugin monitor

- debian/changelog
Bump version to 6.0.29
Log: Bump version to 6.0.29
> chore: Bump version to 6.0.29

- deepin-devicemanager/src/DeviceManager/DeviceInfo.cpp
- deepin-devicemanager/src/DeviceManager/DeviceInfo.h
support lupdate auto
Log:  support lupdate auto
Bug: https://pms.uniontech.com/task-view-368603.html
> chore: [translate] support lupdate auto

- deepin-devicemanager/src/DeviceManager/DeviceMonitor.cpp
fix the flmx device of monitor display
Log: fix the flmx device of monitor display
Task: https://pms.uniontech.com/task-view-368603.html
> fix: the flmx device of monitor display

- deepin-devicemanager/src/DeviceManager/DeviceInfo.cpp
- deepin-devicemanager/src/DeviceManager/DeviceInfo.h
- deepin-devicemanager/src/DeviceManager/DeviceNetwork.cpp
get the network of usb vender info
Log: get the network of usb vender info
Task: https://pms.uniontech.com/task-view-368603.html
> fix: get the network of usb vender info

- deepin-devicemanager/src/DeviceManager/DeviceNetwork.cpp
add communication network  support
Log:  add communication network  support
Bug: https://pms.uniontech.com/task-view-360593.html
> fix: [network] add communication network  support

- deepin-devicemanager/src/DeviceManager/DeviceMonitor.cpp
- deepin-devicemanager/translations/deepin-devicemanager_zh_CN.ts
fix the w515 device of monitor display
Log: fix the w515 device of monitor display
Task: https://pms.uniontech.com/task-view-368603.html
> fix: the w515 device of monitor display

- deepin-devicemanager/src/DeviceManager/DeviceMonitor.cpp
fix the w525 device of monitor display
Log: fix the w525 device of monitor display
Task: https://pms.uniontech.com/task-view-368603.html
> fix: the w525 device of monitor display

- deepin-devicemanager-server/src/DriverControl/DriverManager.cpp
remove invalid  url
Log: remove invalid  url
> fix: remove invalid  url

- deepin-devicemanager/src/GenerateDevice/DeviceGenerator.cpp
fix the bluetooth of false identification
Log: fix the bluetooth of false identification
Task: https://pms.uniontech.com/task-view-360593.html
Change-Id: I56de4352eed27414aba935daa97cd72ef76dd309
> fix: the bluetooth of false identification

- deepin-devicemanager/src/DeviceManager/DeviceMonitor.cpp
fix the device of monitor display
Log: fix the device of monitor display
Bug: https://pms.uniontech.com/bug-view-296425.html
https: //pms.uniontech.com/bug-view-296689.html
Change-Id: Ief79bbd158fef4f7a2b9332ec87e82246cd55a87
> fix: the device of monitor display

- deepin-devicemanager/src/DeviceManager/DeviceMonitor.cpp
fix the monitor fresh rate
Log: fix the monitor fresh rate
Bug: https://pms.uniontech.com/bug-view-297753.html
> fix: the monitor fresh rate

- deepin-devicemanager/src/DeviceManager/DeviceMonitor.cpp
fix the monitor paramer
Log: fix the monitor paramer
Bug: https://pms.uniontech.com/bug-view-297753.html
> fix: the monitor paramer

- deepin-devicemanager/src/DeviceManager/DeviceStorage.cpp
fix the storage display
Log: fix the storage display
Bug: https://pms.uniontech.com/bug-view-297753.html
> fix: the storage siez display

- deepin-devicemanager/src/DeviceManager/DeviceMonitor.cpp
- deepin-devicemanager/src/Tool/ThreadExecXrandr.cpp
fix the monitor get info from xrander
Log: fix the monitor get info from xrander
Bug: https://pms.uniontech.com/bug-view-285297.html
> fix: the monitor get info from xrander

- deepin-devicemanager-server/deepin-deviceinfo/src/hotplug/monitorusb.cpp
adjust the select usb timeout, change the timeout 0.01s to 1s.
Log: adjust the select usb timeout, change the timeout 0.01s to 1s.
> fix: adjust the select usb timeout

- deepin-devicemanager/src/GenerateDevice/HWGenerator.cpp
fit the UFS for klv
Log: fit the UFS for klv
Change-Id: I435e4f59b113164fe5a6138c869c85384e1cf5f2
> fix: fit the UFS for klv

- deepin-devicemanager/configs/org_deepin_devicemanager.hpp
Add org_deepin_devicemanager.hpp for DConfig integration
Log: add DConfig support for device manager
> feat: add DConfig support for device manager

- debian/control
> fix: dependency supplement

- deepin-devicemanager-server/deepin-deviceinfo/src/hotplug/monitorusb.cpp
Reverts linuxdeepin/deepin-devicemanager#414
> Revert "fix: adjust the select usb timeout"

- deepin-devicemanager/src/DeviceManager/DeviceStorage.cpp
add the storage overview info
Log: add the storage overview info
Task: https://pms.uniontech.com/task-view-372725.html
> feat: add the storage overview info

- deepin-devicemanager/src/DeviceManager/DeviceStorage.cpp
modify the storage size
Log: modify the storage size
Task: https://pms.uniontech.com/task-view-372725.html
> feat: modify the storage size

- deepin-devicemanager/src/GenerateDevice/HWGenerator.cpp
- deepin-devicemanager/src/Tool/ThreadExecXrandr.cpp
fix the get info from edit in order
read the edid info from system may not in order.
Log: fix the get info from edit in order
Bug: https://pms.uniontech.com/bug-view-305295.html
> fix: the get info from edit in order

- debian/changelog
update changelog 6.0.35
Log: update changelog 6.0.35
> chore: update changelog 6.0.35

- deepin-devicemanager/src/DeviceManager/DeviceMonitor.cpp
fix the monitor info in single screen mode.
Log: fix the monitor info in single screen mode.
Bug: https://pms.uniontech.com/bug-view-305295.html
> fix: the monitor info in single screen mode

- debian/changelog
update changelog 6.0.36
Log: update changelog 6.0.36
> chore: update changelog 6.0.36

- debian/changelog
update changelog 6.0.37
Log: update changelog 6.0.37
> chore: update changelog 6.0.37wq

- .tx/config
- deepin-devicemanager/translations/deepin-devicemanager.ts
update translation config
Log: update translation config
> chore: update translation config

- deepin-devicemanager/translations/deepin-devicemanager.ts
update tanslation
Log: update translation ts
> chore: update translation ts

- deepin-devicemanager/src/DeviceManager/DeviceInput.cpp
- deepin-devicemanager/src/DeviceManager/DeviceInput.h
- deepin-devicemanager/src/Page/PageMultiInfo.cpp
- deepin-devicemanager/src/Page/PageSingleInfo.cpp
- deepin-devicemanager/src/Widget/TableWidget.cpp
fix wakeup ps/2 mouse
Log: fix wakeup ps/2 mouse.
Bug: https://pms.uniontech.com/bug-view-313055.html
> fix: fix wakeup ps/2 mouse

- .gitignore
- deepin-devicemanager/CMakeLists.txt
- deepin-devicemanager/src/EnableControl/DBusTouchPad.cpp
- deepin-devicemanager/src/Tool/ThreadExecXrandr.cpp
- deepin-devicemanager/src/WakeupControl/DBusWakeupInterface.cpp
- deepin-devicemanager/src/main.cpp
As title.
Log: Adapt to V23 dde dbus interface
> refactor: Detecting the system version at runtime

- deepin-devicemanager/src/DeviceManager/DeviceComputer.cpp
- deepin-devicemanager/src/DeviceManager/DeviceCpu.cpp
- deepin-devicemanager/src/DeviceManager/DeviceImage.cpp
- deepin-devicemanager/src/DeviceManager/DeviceInput.cpp
- deepin-devicemanager/src/DeviceManager/DeviceMemory.cpp
- deepin-devicemanager/src/DeviceManager/DeviceMonitor.cpp
- deepin-devicemanager/src/DeviceManager/DeviceNetwork.cpp
- deepin-devicemanager/src/DeviceManager/DeviceOtherPCI.cpp
- deepin-devicemanager/src/DeviceManager/DeviceOthers.cpp
- deepin-devicemanager/src/DeviceManager/DevicePower.cpp
- deepin-devicemanager/src/DeviceManager/DevicePrint.cpp
- deepin-devicemanager/src/DeviceManager/DeviceStorage.cpp
-- Variable 'ret' is reassinged a value befor the old one has been used.
> Chore: [cppcheck] Resolve issue identified by cppcheck
