linuxdeepin/deepin-devicemanager

deepin-devicemanager-server/src/HotPlug/MonitorUsb.cpp

开机10秒后再多取一次信息。
Log: 修复MOH指纹模块显示不可用
Bug: https://pms.uniontech.com/bug-view-141439.html

fix: 修复MOH 指纹模块取不到driver，显示不可用

---

deepin-devicemanager/src/DeviceManager/DeviceBluetooth.cpp
deepin-devicemanager/src/DeviceManager/DeviceManager.cpp

重复蓝牙导致自动识别为不可用
Log: 正常显示多个蓝牙设备
Bug: https://pms.uniontech.com/bug-view-131523.html

fix: 设备管理器多个蓝牙显示不可用

---

deepin-devicemanager-server/src/HotPlug/MonitorUsb.cpp
deepin-devicemanager/src/DeviceManager/DeviceOthers.cpp
deepin-devicemanager/src/GenerateDevice/DeviceGenerator.cpp

取消指纹模块driver为空的判为“显示不可用 ”,让MOH和FT9201 指纹模块显示可用
Log: 修复MOH指纹模块显示不可用
Bug: https://pms.uniontech.com/bug-view-141439.html

fix: 支持MOH和FT9201 指纹模块取不到driver，显示可用

---

deepin-devicemanager/src/DeviceManager/DeviceBluetooth.cpp

驱动管理里蓝牙显示型号
Log: 正确显示蓝牙
/review @pengfeixx

fix: 驱动管理里蓝牙显示错误

---

deepin-devicemanager/src/Page/PageListView.cpp
deepin-devicemanager/src/Widget/DeviceListView.cpp

取消选择空隙选中概况
Log:  点击主界面左侧目录之间的间隙时不应触发显示概况
Bug: https://pms.uniontech.com/bug-view-151783.html
/review @pengfeixx @feeengli @jeffshuai

fix: 点击主界面左侧目录之间的间隙时不应触发显示概况且目录概况未被选中

---

deepin-devicemanager/src/DeviceManager/DeviceMemory.cpp
deepin-devicemanager/src/DeviceManager/DeviceMonitor.cpp
deepin-devicemanager/src/GenerateDevice/DeviceFactory.cpp
deepin-devicemanager/src/GenerateDevice/DeviceGenerator.cpp
deepin-devicemanager/src/GenerateDevice/PanguVGenerator.cpp
deepin-devicemanager/src/GenerateDevice/PanguVGenerator.h
deepin-devicemanager/src/Tool/EDIDParser.cpp

添加读取edid显示设备；更新cpu数量计算方法；
Log: 正确显示显示设备和cpu个数
Bug: https://pms.uniontech.com/bug-view-152007.html
/review @pengfeixx @jeffshuai @feeengli @hundundadi @myk1343

fix: 设备管理器没有显示设备信息

---

deepin-devicemanager/src/GenerateDevice/DeviceGenerator.cpp

禁用显卡音频，重启后音频信息异常增多because of from lshw
Log: 修复禁用显卡音频，重启后音频信息异常增多
Bug: https://pms.uniontech.com/bug-view-150331.html

fix: 禁用显卡音频，重启后音频信息异常增多

---

deepin-devicemanager/src/DeviceManager/DeviceAudio.cpp

去除重复的制造商和型号信息
Log: 正常显示音频硬件设备信息
Bug: https://pms.uniontech.com/bug-view-153955.html

fix: 音频硬件设备信息制造商和型号信息重复显示

---

deepin-devicemanager/src/Tool/ThreadExecXrandr.cpp

正则表达式只取了2位数据
Log: 正常显示显示器的刷新率
Bug: https://pms.uniontech.com/bug-view-154667.html
/review @lzwind @feeengli @hundundadi @jeffshuai @myk1343

fix: 144HZ显示器在设备管理器中显示为44HZ

---

deepin-devicemanager/src/Page/MainWindow.cpp
deepin-devicemanager/src/Tool/ThreadExecXrandr.cpp
deepin-devicemanager/src/Tool/ThreadExecXrandr.h
deepin-devicemanager/tests/src/GenerateDevice/ut_loadinfothread.cpp

使用dbus的最大最小分辨率
Log: 正确显示分辨率
Bug: https://pms.uniontech.com/bug-view-151709.html
/review @lzwind @feeengli @hundundadi @jeffshuai @myk1343

fix: 设备管理器中显示适配器中最大分辨率和最小分辨率信息有误

---

deepin-devicemanager/src/DeviceManager/DeviceAudio.cpp

添加声卡厂商和型号
Log: 正确显示声卡厂商和型号
/review @lzwind @myk1343 @pengfeixx @feeengli @hundundadi @jeffshuai

fix: hw声卡厂商和型号未显示

---

deepin-devicemanager-server/deepin-devicemanager-server.service

将设备管理器服务调整到netwark之后启动
Log: 重启正常显示
Bug: https://pms.uniontech.com/bug-view-146857.html
/review @lzwind @feeengli @jeffshuai @hundundadi @myk1343 @pengfeixx

fix: 设备管理器只有概况信息

---

deepin-devicemanager-server/src/LoadInfo/cpu/CoreCpu.cpp

fix: 部分CPU核心ID存在间隔问题

---

deepin-devicemanager/src/DeviceManager/DeviceNetwork.cpp
deepin-devicemanager/src/DeviceManager/DeviceNetwork.h

自定义网络适配器表头
Log: 网络适配器表头显示类型
Bug: https://pms.uniontech.com/bug-view-161717.html
/review @lzwind @feeengli @jeffshuai @myk1343 @pengfeixx @HeeMingYang

fix: 存在多个网络适配器时列表中的title应显示类型而非型号

---

deepin-devicemanager/src/DeviceManager/DeviceAudio.cpp
deepin-devicemanager/src/DeviceManager/DeviceGpu.cpp
deepin-devicemanager/src/DeviceManager/DeviceNetwork.cpp
deepin-devicemanager/src/DeviceManager/DeviceOtherPCI.cpp

隐藏显卡声卡网卡的PCI时钟频率和位宽
Log: 隐藏显卡声卡网卡的时钟频率和位宽
Bug: https://pms.uniontech.com/bug-view-160181.html,https://pms.uniontech.com/bug-view-159585.html
/review @pengfeixx @feeengli @jeffshuai @HeeMingYang

fix: 显卡声卡网卡的时钟频率和位宽错误

---

deepin-devicemanager/CMakeLists.txt
deepin-devicemanager/tests/CMakeLists.txt

1.  linuxdeepin/developer-center#3345 的一部分， --as-need 会破坏部分链接器
2. 和 https://github.com/linuxdeepin/deepin-calculator/pull/82 相同，不要直接覆盖 CMAKE_EXE_LINKER_FLAGS

fix: use as-needed instead of as-need and don't ignore linker flags 

---

deepin-devicemanager/src/Widget/DeviceListView.cpp

侧边栏边距设置为11像素
Log: 居中显示侧边栏内容
Bug: https://pms.uniontech.com/bug-view-157697.html

fix: 侧边栏hover/高亮时背景底没有与侧边栏居中对齐

---

deepin-devicemanager/src/Widget/DetailTreeView.cpp

表格分割线透明度设置为20
Log: 正确显示表格分割线
Bug: https://pms.uniontech.com/bug-view-157693.html

fix: 表格分割线看不清

---

deepin-devicemanager/src/DeviceManager/DeviceAudio.cpp
deepin-devicemanager/src/DeviceManager/DeviceInfo.cpp

去掉芯片信息换行符
Log: 正确显示音频适配器芯片信息
Bug: https://pms.uniontech.com/bug-view-162727.html

fix: 音频适配器芯片信息显示不全

---

deepin-devicemanager/src/Widget/DetectedStatusWidget.cpp

fix: 切换驱动后关闭出现coredump

---

deepin-devicemanager/src/DeviceManager/DeviceGpu.cpp

通过lshw更正显示适配器名称
Log: 正常显示显示适配器名称
Bug: https://pms.uniontech.com/bug-view-157195.html

fix: 显示适配器显示pci

---

deepin-devicemanager/src/Widget/DriverScanWidget.cpp

驱动扫描后停止刷新动画
Log: 正确使用cpu资源
Bug: https://pms.uniontech.com/bug-view-169563.html

fix: 驱动扫描后cpu占用未恢复到扫描前的状态

---

deepin-devicemanager/src/DeviceManager/DeviceMemory.cpp

将dmidecode17查询的内存速率替换lshw信息
Log: 正确显示内存速率
Bug: https://pms.uniontech.com/bug-view-169555.html

fix: 设备管理器中内存单位与终端中输入dmidecode17查询的内存速率单位不符合

---

deepin-devicemanager/src/Page/PageDriverManager.cpp

关闭应用时取消扫描线程
Log: 正常关闭
Bug: https://pms.uniontech.com/bug-view-164681.html

fix: 进入驱动管理并在它正在加载的时候关闭设备管理器会出现一个用户无感知的崩溃

---

deepin-devicemanager/src/GenerateDevice/CmdTool.cpp

bluetoothctl命令卡住，已限制时间
Log: 正确显示设备管理器信息
Bug: https://pms.uniontech.com/bug-view-163665.html

fix: 设备管理器无法显示设备信息且光标一直在转圈

---

deepin-devicemanager/src/DeviceManager/DeviceInput.cpp
deepin-devicemanager/src/WakeupControl/DBusWakeupInterface.cpp
deepin-devicemanager/src/WakeupControl/DBusWakeupInterface.h

通过dde-daemon设置鼠标唤醒功能
Log: 正常设置鼠标唤醒
Bug: https://pms.uniontech.com/bug-view-172035.html

fix: 设置鼠标唤醒后从一个USB接口更换到其他USB接口后再S3后USB鼠标无法唤醒需要重新刷新后设置或重新开启设备管理器后再重新设置

---

deepin-devicemanager/src/GenerateDevice/CmdTool.cpp

减少bluetoothctl命令查询时间
Log: 优化启动时间

fix: bluetoothctl命令卡死导致查询时间变长

---

deepin-devicemanager/src/DeviceManager/DeviceStorage.cpp

通过smartctl读取磁盘大小
Log: 正确显示存储设备信息
Bug: https://pms.uniontech.com/bug-view-176439.html

fix: 设备管理器显示的存储设备信息显示不正确

---

deepin-devicemanager/src/DeviceManager/DeviceCpu.cpp

去掉处理器当前实时频率显示
Log: 去掉处理器当前实时频率显示
Bug: https://pms.uniontech.com/bug-view-143719.html

fix: 设备管理器未正确获取处理器当前实时频率

---

deepin-devicemanager/src/DeviceManager/DeviceInfo.cpp

usb的key值转换失败
Log: 正确打开应用
Bug: https://pms.uniontech.com/bug-view-181737.html

fix: 部分机型打开设备管理器窗口闪退不能正常打开

---

deepin-devicemanager/src/GenerateDevice/HWGenerator.cpp

部分机型显示蓝牙
Log: 显示蓝牙设备
Bug: https://pms.uniontech.com/bug-view-183587.html

fix: 设备管理器中显示蓝牙不可用

---

deepin-devicemanager/src/DeviceManager/DeviceBluetooth.cpp
deepin-devicemanager/src/DeviceManager/DeviceImage.cpp
deepin-devicemanager/src/DeviceManager/DeviceInput.cpp
deepin-devicemanager/src/DeviceManager/DeviceOthers.cpp
deepin-devicemanager/src/GenerateDevice/HWGenerator.cpp
deepin-devicemanager/src/commonfunction.cpp

隐藏无效设备序列号和部分机型显示蓝牙
Log: 隐藏无效设备序列号和显示蓝牙设备
Bug: https://pms.uniontech.com/bug-view-183587.html

fix: 设备序列号乱码和设备管理器中显示蓝牙不可用 

---

deepin-devicemanager/src/DeviceManager/DeviceGpu.cpp

显卡型号统一为设备名称
Log: 显卡型号统一为设备名称
Bug: https://pms.uniontech.com/bug-view-173765.html

fix: 显卡型号错误

---

deepin-devicemanager/src/DeviceManager/DeviceInput.cpp

置灰ps2的接口鼠标的禁用按钮
Log: 置灰ps2的接口鼠标的禁用按钮
Bug: https://pms.uniontech.com/bug-view-181705.html

fix: ps2的接口鼠标无法禁用

---

deepin-devicemanager/src/DeviceManager/DeviceNetwork.cpp

通过SysFS ID获取设备路径
Log: 正确禁用网络适配器
Bug: https://pms.uniontech.com/bug-view-184291.html

fix: 网络适配器禁用失败

---

deepin-devicemanager/src/Widget/DetailTreeView.cpp

DetailTreeView清空数据时未将当前用于显示tips的item置为空
Log: 正常刷新界面
Bug: https://pms.uniontech.com/bug-view-181085.html,https://pms.uniontech.com/bug-view-185727.html

fix: 修改右键刷新界面coredump

---

deepin-devicemanager/src/Widget/DetailTreeView.cpp
deepin-devicemanager/src/Widget/DetailTreeView.h

鼠标右键点击时主动隐藏tooltip
Log: 正常显示右键菜单
Bug: https://pms.uniontech.com/bug-view-185777.html

fix: 右键菜单和tooltip内容同时展示

---

deepin-devicemanager/src/DeviceManager/DeviceNetwork.cpp
deepin-devicemanager/src/DeviceManager/DeviceNetwork.h
deepin-devicemanager/src/GenerateDevice/DeviceGenerator.cpp

HW Address和Permanent HW Address不一致导致lshw网卡匹配失败
Log: 正确显示网卡信息
Bug: https://pms.uniontech.com/bug-view-189671.html

fix: 在系统下设备管理器中网络适配器中未显示板载有线网卡信息

---

deepin-devicemanager/src/DeviceManager/DeviceMonitor.cpp
deepin-devicemanager/translations/deepin-devicemanager_zh_CN.ts

隐藏显示器的生产日期和更新电池第一个容量为最大容量
Log: 隐藏显示器的生产日期和更新电池第一个容量为最大容量

feat: 去掉显示器的生产日期和更新电池容量

---

deepin-devicemanager-server/src/MainJob.cpp
deepin-devicemanager/src/GenerateDevice/CmdTool.cpp

去除多余的framebuffer
Log: 正确显示显示器设备
Bug: https://pms.uniontech.com/bug-view-193741.html

fix: 只插入一个显示器的情况下设备管理器中显示2个显示设备

---

deepin-devicemanager/src/DeviceManager/DeviceManager.cpp

当两个设备显示时，TOML可能先添加一个设备再复盖一个设备
Log: 修复当两个设备显示时，TOML可能先添加一个设备再复盖一个设备

fix: 修复当两个设备显示时，TOML可能先添加一个设备再复盖一个设备

---

deepin-devicemanager/src/DeviceManager/DeviceNetwork.cpp
deepin-devicemanager/src/GenerateDevice/KLUGenerator.h

设备管理器 概况-网络适配中klu缺少无线的展示 Hi1103-2addKLVU
Log: 设备管理器 概况-网络适配中klu缺少无线的展示 Hi1103addKLVU
Bug: https://pms.uniontech.com/bug-view-197543.html

fix: 设备管理器 概况-网络适配中klu缺少无线的展示 Hi110addKLVU

---

deepin-devicemanager/src/GenerateDevice/HWGenerator.cpp

设备管理器HW音频适配器相关信息定制为HUAWEI
Log: 设备管理器HW音频适配器相关信息定制为HUAWEI
Bug: https://pms.uniontech.com/bug-view-190965.html

fix: 设备管理器PGW未展示音频适配器相关信息

---

deepin-devicemanager/src/DriverControl/DriverScanner.cpp

设备管理器在驱动管理的检测过程中进入待机状态，会立即断网
Log: 修复设备管理器在驱动管理的检测过程中立即断网，检测过程一直扫描状态
Bug: https://pms.uniontech.com/bug-view-202141.html

fix: 修复设备管理器在驱动管理的检测过程中立即断网，检测过程一直扫描状态

---

deepin-devicemanager/assets/org.deepin.devicemanager.json
deepin-devicemanager/src/commonfunction.cpp

Description: 修改默认配置值为-1,存在dconfig接口但是底层未修改配置文件时，将采用以前判断hw的方式
Log: hw机型判断适配dconfig
Task: https://pms.uniontech.com/task-view-276433.html

feat: hw机型判断适配dconfig

---

debian/changelog
deepin-devicemanager/src/DeviceManager/DeviceStorage.cpp

修复当两个U盘序列号一致时不正常情况下 被误合并为一个
Log: 适配当两个序列号一致的U盘

fix: 适配当两个序列号一致的U盘

---

deepin-devicemanager/src/DeviceManager/DeviceMonitor.cpp
deepin-devicemanager/src/Tool/EDIDParser.cpp

修复显示设备-大小和hwinfo命令获取内容不一致
Log: 显示设备-大小和hwinfo命令获取内容不一致
Bug: https://pms.uniontech.com/bug-view-216003.html

fix: 显示设备-大小和hwinfo命令获取内容不一致

---

deepin-devicemanager/src/DeviceManager/DeviceOthers.cpp
deepin-devicemanager/src/DeviceManager/DeviceOthers.h
deepin-devicemanager/src/GenerateDevice/CmdTool.cpp
deepin-devicemanager/src/GenerateDevice/LoadInfoThread.cpp

修复“其它设备”驱动为空时显示不可用
修复正在查询信息时关闭窗口导致程序无法退出Commit_id e5e465c5
Log: 修复“其它设备”驱动为空时显示不可用
Bug: https://pms.uniontech.com/bug-view-203907.html (cherry picked from commit 5769d210c534db2ce8c6a9e751685676710054bc)

fix: 修复“其它设备”驱动为空时显示不可用

---

deepin-devicemanager-server/deepin-devicecontrol/src/controlinterface.cpp
deepin-devicemanager-server/deepin-devicecontrol/src/controlinterface.h
deepin-devicemanager-server/deepin-devicecontrol/src/drivercontrol/drivermanager.h
deepin-devicemanager/src/DriverControl/DBusDriverInterface.cpp
deepin-devicemanager/src/DriverControl/DBusDriverInterface.h
deepin-devicemanager/src/DriverControl/DriverBackupThread.cpp
deepin-devicemanager/src/DriverControl/DriverBackupThread.h
deepin-devicemanager/src/Page/PageDriverManager.cpp

修复一键备份部分驱动备份失败失败,鉴权弹框长时间静止不操作提示失败问题
Log: 修复一键备份部分驱动备份失败失败,鉴权弹框长时间静止不操作提示失败问题
Bug: https://pms.uniontech.com/bug-view-226193.html
https://pms.uniontech.com/bug-view-226257.html

fix: 一键备份部分驱动备份失败失败,鉴权弹框长时间静止不操作提示失败

---

deepin-devicemanager/src/DriverControl/DriverBackupThread.cpp
deepin-devicemanager/src/DriverControl/DriverBackupThread.h
deepin-devicemanager/src/Page/PageDriverManager.cpp

修复一键备份点击取消按钮不能终止流程问题
Log: 修复一键备份点击取消按钮不能终止流程问题
Bug: https://pms.uniontech.com/bug-view-226197.html

fix: 一键备份点击取消不能终止流程

---

deepin-devicemanager/src/DeviceManager/DeviceStorage.cpp

1.02TB问题修改
Log: 1.02TB问题修改
Bug: https://pms.uniontech.com/bug-view-211013.html

fix: 1.02TB问题修改

---

deepin-devicemanager/src/Page/PageDriverManager.cpp
deepin-devicemanager/src/Widget/drivertableview.cpp

修复一键安装时点击取消不能终止流程
Log: 修复一键安装时点击取消不能终止流程
Bug: https://pms.uniontech.com/bug-view-226819.html

fix: 一键安装，点击取消不能终止流程

---

deepin-devicemanager/src/Page/PageDriverInstallInfo.cpp
deepin-devicemanager/src/Page/PageDriverInstallInfo.h
deepin-devicemanager/src/Page/PageDriverManager.cpp
deepin-devicemanager/src/Page/PageDriverRestoreInfo.cpp

修复一键安装时安装失败后无法重新全选，还原页面焦点异常问题
Log: 修复一键安装时安装失败后无法重新全选
Bug: https://pms.uniontech.com/bug-view-226817.html
https://pms.uniontech.com/bug-view-226831.html

fix: 一键安装时安装失败后无法重新全选

---

deepin-devicemanager/src/DriverControl/HttpDriverInterface.cpp

修复驱动安装后依然展示在可更新列表中
Log: 修复驱动安装后依然展示在可更新列表中、
Bug: https://pms.uniontech.com/bug-view-227215.html

fix: 驱动安装后依然展示在可更新列表中

---

deepin-devicemanager/src/DeviceManager/DeviceInput.cpp
deepin-devicemanager/src/Page/PageSingleInfo.cpp
deepin-devicemanager/src/WakeupControl/DBusWakeupInterface.cpp
deepin-devicemanager/src/WakeupControl/DBusWakeupInterface.h
deepin-devicemanager/src/Widget/TextBrowser.cpp

修复待机后不能通过PS2鼠标唤醒
Log: 修复待机后不能通过PS2鼠标唤醒
Bug: https://pms.uniontech.com/bug-view-219597.html

fix: 待机后不能通过PS2鼠标唤醒

---

deepin-devicemanager/src/DeviceManager/DeviceAudio.cpp
deepin-devicemanager/src/DeviceManager/DeviceStorage.cpp

修复部分设备 “物理ID”和“模块别名”重复显示
Log: 修复部分设备 “物理ID”和“模块别名”重复显示
Bug: https://pms.uniontech.com/bug-view-228921.html

fix: 部分设备“物理ID”和“模块别名”重复显示

---

debian/changelog
deepin-devicemanager/src/Page/PageDetail.cpp

修复页面中“更多”按钮后没有更多
Log:  修复页面中“更多”按钮后没有更多
Bug: https://pms.uniontech.com/bug-view-218277.html

fix: 修复页面中“更多”按钮后没有更多

---

deepin-devicemanager/src/DeviceManager/DeviceInput.cpp

修复当为PS2键盘置灰允许唤起电脑该功能
Log:  修复当为PS2键盘置灰允许唤起电脑该功能
Bug: https://pms.uniontech.com/bug-view-237867.html

fix: 修复当为PS2键盘置灰允许唤起电脑该功能

---

deepin-devicemanager/src/DriverControl/DriverScanner.cpp

aptupdate前驱动扫描过程中必现设备管理器窗口崩溃
Log:  aptupdate前驱动扫描过程中必现设备管理器窗口崩溃
Bug: https://pms.uniontech.com/bug-view-238513.html

fix: 修复驱动扫描过程中必现设备管理器窗口崩溃

---

deepin-devicemanager/src/DeviceManager/DeviceStorage.cpp

smartctl的serial number和设备管理器的序列号不一样
Log:  取smartctl保持一致
Bug: https://pms.uniontech.com/bug-view-230865.html

fix: 修复部分cid磁盘设备管理器的序列号

---

deepin-devicemanager/src/DeviceManager/DeviceManager.cpp

修复“硬件信息”页面快速点击左侧导航栏后，点击界面上方的“驱动管理”，应用会发生闪退
Log: 修复“硬件信息”页面快速点击左侧导航栏后，点击界面上方的“驱动管理”，应用会发生闪退
Bug: https://pms.uniontech.com/bug-view-243127.html

fix: “硬件信息”页面快速点击左侧导航栏后，点击界面上方的“驱动管理”，应用会发生闪退

---

deepin-devicemanager-server/deepin-devicecontrol/src/controlinterface.cpp
deepin-devicemanager-server/deepin-devicecontrol/src/controlinterface.h
deepin-devicemanager-server/deepin-devicecontrol/src/drivercontrol/drivermanager.cpp
deepin-devicemanager-server/deepin-devicecontrol/src/drivercontrol/drivermanager.h
deepin-devicemanager/src/DriverControl/DBusDriverInterface.cpp
deepin-devicemanager/src/DriverControl/DBusDriverInterface.h
deepin-devicemanager/src/DriverControl/DriverBackupThread.cpp

修复仓库未更新时无法下载驱动进行备份
Log: 修复仓库未更新时无法下载驱动进行备份
https://pms.uniontech.com/bug-view-242971.html

fix: 仓库未更新时无法备份驱动

---

deepin-devicemanager/src/GenerateDevice/DeviceGenerator.cpp

修复sw机型中内存显示
Log:  修复sw机型中内存显示
Bug: https://pms.uniontech.com/bug-view-219863.html

fix: 修复sw机型中内存显示

---

debian/changelog
deepin-devicemanager/src/commonfunction.cpp

据湛生20231224邮修改
Log:  add  t11string4 for PguX

feat: 某新PGX机进行额外适配

---

deepin-devicemanager-server/deepin-deviceinfo/deepin-deviceinfo.json

由deepin-service-manager 控制延时3秒启动
Log:  由deepin-service-manager 控制延时3秒启动
Bug: https://pms.uniontech.com/bug-view-238905.html

fix:  由deepin-service-manager 控制延时3秒启动服务端

---

deepin-devicemanager/src/GenerateDevice/HWGenerator.cpp

剔除错误识别判断
Log: U盘介质识别错误
Bug: https://pms.uniontech.com/bug-view-250575.html

fix: U盘介质识别错误

---

deepin-devicemanager/src/DeviceManager/DeviceInput.cpp
deepin-devicemanager/src/DeviceManager/DeviceInput.h

鼠标在不能用的情况下，解决能用鼠标唤醒的问题
Log: 记录状态，禁用之前，将唤醒能力关掉;启动时，再将唤醒能力打开。
Bug: https://pms.uniontech.com/bug-view-254187.html

fix: 鼠标在不能用的情况下，解决能用鼠标唤醒的问题

---

deepin-devicemanager-server/deepin-devicecontrol/src/enablecontrol/enableutils.cpp

ioctlEnableNetwork-> ioctlOperateNetworkLogicalName, in this function directly to the user input parameter path, strcpy gives ifr.ifr_name a stack overflow
Log: overflow bug (strcpy)
Bug: https://pms.uniontech.com/bug-view-253863.html

fix: the overflow bug of the stack in deepin-devicemanager

---

deepin-devicemanager/src/DeviceManager/DeviceInput.cpp

鼠标禁用前后，调整唤醒能力状态
Log: 鼠标禁用前后，调整唤醒能力状态
Bug: https://pms.uniontech.com/bug-view-254187.html

fix: 鼠标禁用前后，调整唤醒能力状态

---

deepin-devicemanager/src/Page/MainWindow.cpp
deepin-devicemanager/src/Page/MainWindow.h

增加UPower服务的刷新接口，解决电池状态显示延迟
Log: 增加UPower服务的刷新接口，解决电池状态显示延迟
Bug: https://pms.uniontech.com/bug-view-254185.html

fix: 增加UPower服务的刷新接口，解决电池状态显示延迟

---

deepin-devicemanager/src/DeviceManager/DeviceStorage.cpp

部分UFS设备接口信息显示为UFS31
Log:  部分UFS设备接口信息显示为UFS31
Bug: https://pms.uniontech.com/bug-view-251373.html

fix:  部分设备接口信息显示为UFS31

---

deepin-devicemanager/src/Page/MainWindow.cpp

电池的UPower服务刷新接口
Log: 电池的UPower服务刷新接口
Bug: https://pms.uniontech.com/bug-view-254185.html

fix: 电池的UPower服务刷新接口

---

deepin-devicemanager/src/DeviceManager/DeviceAudio.cpp

修复部分设备sysfs的设备设置驱动信息
Log: 修复部分设备卸载驱动时问题
Bug: https://pms.uniontech.com/bug-view-262223.html

fix:  修复卸载驱动会弹出未发现该驱动模块错误

---

deepin-devicemanager/src/DeviceManager/DeviceOthers.cpp

依据hwinfo的"cfg_avail=yes"作可用
Log: 修复其它设备中指纹不可用
Bug: https://pms.uniontech.com/bug-view-262721.html

fix:  修复其它设备中不可用情况

---

deepin-devicemanager/src/Page/MainWindow.cpp

禁用USB设备退出重启应用
Log:  显示不可用
Bug: https://pms.uniontech.com/bug-view-269251.html

fix: 禁用USB设备再重启启用后显示不可用

---

deepin-devicemanager/src/WakeupControl/DBusWakeupInterface.cpp
deepin-devicemanager/src/commonfunction.cpp

adpator V23 dde for PS2 mouse wakeup
Log:  adpator V23 dde for PS2 mouse wakeup
Bug: https://pms.uniontech.com/bug-view-271823.html

fix:  adpator V23 dde for PS2 mouse wakeup

---

deepin-devicemanager-server/src/EnableControl/DBusEnableInterface.cpp
deepin-devicemanager-server/src/EnableControl/DBusEnableInterface.h

add polkit support for root app
Log: add polkit support for root app
Bug: https://pms.uniontech.com/bug-view-273929.html

fix: add polkit support for root app

---

deepin-devicemanager-server/deepin-deviceinfo/src/mainjob.cpp
deepin-devicemanager-server/deepin-deviceinfo/src/mainjob.h

after S3 wakeup, some hardware not really wakeup and ready
Log:  S3 wakeup init hardware must delay
Bug: https://pms.uniontech.com/bug-view-273929.html

fix: after S3 wakeup init hardware must delay

---

deepin-devicemanager/src/main.cpp

move polkit after SingleInstance
Log:  add polkit support setSingleInstance
Task:https://pms.uniontech.com/task-view-364005.html

chore: [security] add polkit with setSingleInstance

---

deepin-devicemanager/src/Tool/EDIDParser.cpp

Acording the edid spec, the screen size width 15 and height 16
Log:  follow the edit spec
Bug: https://pms.uniontech.com/bug-view-277559.html

fix: 显示屏幕尺寸异常

---

debian/install
debian/rules

1.Resolve the issue of empty device information display
2.Fix the issue of incomplete packaging content in the deb package
Log: Fix the issue of incomplete packaging content in the deb package
Bug: https://pms.uniontech.com/bug-view-281813.html

fix: Resolve the issue of empty device information display

---

deepin-devicemanager-server/deepin-devicecontrol/src/drivercontrol/drivermanager.cpp
deepin-devicemanager-server/deepin-devicecontrol/src/drivercontrol/utils.cpp
deepin-devicemanager-server/deepin-devicecontrol/src/drivercontrol/utils.h

* Fix executeServerCmd() to get command results correctly;
* If hierarchical verification is enabled, we assume that all packages are signed.
Log: Fixed the issue that deb verify failed.

fix: fixed the issue that deb verify failed

---

deepin-devicemanager/assets/oeminfo_sampleAnduseGuideLine_zh_CN.toml
deepin-devicemanager/assets/org.deepin.devicemanager.json
deepin-devicemanager/src/DeviceManager/DeviceAudio.cpp
deepin-devicemanager/src/DeviceManager/DeviceBios.cpp
deepin-devicemanager/src/DeviceManager/DeviceBluetooth.cpp
deepin-devicemanager/src/DeviceManager/DeviceBluetooth.h
deepin-devicemanager/src/DeviceManager/DeviceCdrom.cpp
deepin-devicemanager/src/DeviceManager/DeviceCpu.cpp
deepin-devicemanager/src/DeviceManager/DeviceGpu.cpp
deepin-devicemanager/src/DeviceManager/DeviceImage.cpp
deepin-devicemanager/src/DeviceManager/DeviceInfo.cpp
deepin-devicemanager/src/DeviceManager/DeviceInput.cpp
deepin-devicemanager/src/DeviceManager/DeviceManager.cpp
deepin-devicemanager/src/DeviceManager/DeviceManager.h
deepin-devicemanager/src/DeviceManager/DeviceMonitor.cpp
deepin-devicemanager/src/DeviceManager/DeviceNetwork.cpp
deepin-devicemanager/src/DeviceManager/DeviceNetwork.h
deepin-devicemanager/src/DeviceManager/DeviceOthers.cpp
deepin-devicemanager/src/DeviceManager/DevicePower.cpp
deepin-devicemanager/src/DeviceManager/DevicePrint.cpp
deepin-devicemanager/src/DeviceManager/DeviceStorage.cpp
deepin-devicemanager/src/GenerateDevice/CmdTool.cpp
deepin-devicemanager/src/GenerateDevice/DeviceGenerator.cpp
deepin-devicemanager/src/GenerateDevice/HWGenerator.cpp
deepin-devicemanager/src/GenerateDevice/HWGenerator.h
deepin-devicemanager/src/Page/MainWindow.cpp
deepin-devicemanager/src/commonfunction.cpp
deepin-devicemanager/src/commonfunction.h
deepin-devicemanager/src/main.cpp
deepin-devicemanager/translations/deepin-devicemanager_zh_CN.ts

extend toml and uniform some model arm code
Log:  extend toml
Bug: https://pms.uniontech.com/task-view-368603.html

chore: extend toml

---

deepin-devicemanager/src/DeviceManager/DeviceManager.cpp
deepin-devicemanager/src/GenerateDevice/DBusInterface.cpp

support multis lvm /dev/mapper
Log:  support multis lvm /dev/mapper
Bug: https://pms.uniontech.com/bug-view-289313.html

chore: [disk] support multis lvm /dev/mapper

---

deepin-devicemanager/src/GenerateDevice/CmdTool.cpp
deepin-devicemanager/src/GenerateDevice/DeviceGenerator.cpp

add communication network  support
Log:  add communication network  support
Bug: https://pms.uniontech.com/task-view-360593.html

fix: [network] add communication network  support

---

deepin-devicemanager/src/GenerateDevice/HWGenerator.cpp

fix the UFS display
Log: fix the UFS display
Bug: https://pms.uniontech.com/bug-view-276131.html

fix: fix the UFS display

---

deepin-devicemanager/src/DeviceManager/DeviceImage.cpp

fix the camera info show incorrect
Log: fix the camera info show incorrect
Bug: https://pms.uniontech.com/bug-view-290539.html

fix: the camera info show incorrect

---

deepin-devicemanager-server/deepin-devicecontrol/CMakeLists.txt
deepin-devicemanager/CMakeLists.txt
deepin-devicemanager/src/DeviceManager/DeviceGpu.cpp
deepin-devicemanager/src/DeviceManager/DeviceInfo.cpp
deepin-devicemanager/src/DriverControl/DriverBackupThread.cpp
deepin-devicemanager/src/GenerateDevice/CmdTool.cpp
deepin-devicemanager/src/GenerateDevice/HWGenerator.cpp
deepin-devicemanager/src/GenerateDevice/KLUGenerator.cpp
deepin-devicemanager/src/GenerateDevice/PanguVGenerator.cpp
deepin-devicemanager/src/Page/PageBoardInfo.cpp
deepin-devicemanager/src/Page/PageDriverManager.cpp
deepin-devicemanager/src/WakeupControl/DBusWakeupInterface.cpp
deepin-devicemanager/tests/CMakeLists.txt

Optimisation submission for qt6 adaptation

fix: Optimisation submission for qt6 adaptation

---

deepin-devicemanager/src/Page/MainWindow.cpp

only set fixed width for ButtonBox instead of fixed size to adapt different themes
Log: adjust ButtonBox width to optimize UI layout
Bug: https://pms.uniontech.com/bug-view-279731.html

fix: adjust ButtonBox width to optimize UI layout

---

deepin-devicemanager/src/DeviceManager/DeviceGpu.cpp
deepin-devicemanager/src/GenerateDevice/DeviceGenerator.cpp
deepin-devicemanager/src/Tool/ThreadExecXrandr.cpp

- Fix resolution parsing regex pattern in xrandr info
- Add empty driver check for GPU uninstall status
- Force display GPU devices from hwinfo
Log: optimize GPU device display and resolution parsing
Bug: https://pms.uniontech.com/bug-view-290469.html

fix: optimize GPU device display and resolution parsing

---

CMakeLists.txt
debian/control
deepin-devicemanager-server/CMakeLists.txt
deepin-devicemanager-server/deepin-devicecontrol/CMakeLists.txt
deepin-devicemanager-server/deepin-deviceinfo/CMakeLists.txt
deepin-devicemanager-server/tests/CMakeLists.txt
deepin-devicemanager/CMakeLists.txt

* Move QT_VERSION_MAJOR=6 to root CMakeLists.txt
* Remove redundant QT_VERSION_MAJOR declarations from sub-projects
* Remove Qt5 related dependencies
* Update libdeepin-service-framework-dev to version >1.0.9
Log: centralize Qt6 version declaration and cleanup dependencies

chore: centralize Qt6 version declaration and cleanup dependencies

---

deepin-devicemanager-server/deepin-devicecontrol/src/drivercontrol/aptinstaller.cpp
deepin-devicemanager-server/deepin-devicecontrol/src/drivercontrol/aptinstaller.h
deepin-devicemanager-server/deepin-devicecontrol/src/drivercontrol/driverinstallerapt.cpp
deepin-devicemanager-server/deepin-devicecontrol/src/drivercontrol/driverinstallerapt.h
deepin-devicemanager-server/deepin-devicecontrol/src/drivercontrol/drivermanager.cpp
deepin-devicemanager-server/deepin-devicecontrol/src/drivercontrol/drivermanager.h
deepin-devicemanager-server/deepin-devicecontrol/src/enablecontrol/enablesqlmanager.cpp
deepin-devicemanager/src/DriverControl/DriverScanner.cpp
deepin-devicemanager/src/Page/PageDriverManager.cpp
deepin-devicemanager/src/Tool/commontools.cpp

* Replace DebInstaller with AptInstaller for package management
* Replace DriverInstaller with DriverInstallerApt for driver installation
* Move database path from /usr/share to /var/lib for better FHS compliance
* Fix array index bounds checking in driver manager pages
Log: migrate driver installation from deb to apt
Task: https://pms.uniontech.com/task-view-373295.html

feat: migrate driver installation from deb to apt

---

deepin-devicemanager-server/deepin-deviceinfo/deepin-deviceinfo.json

Change library name to follow standard naming convention
Log: update deviceinfo library name to standard lib prefix

fix: update deviceinfo library name to standard lib prefix

---

deepin-devicemanager-server/deepin-devicecontrol/src/drivercontrol/httpdriverinterface.cpp
deepin-devicemanager-server/deepin-devicecontrol/src/drivercontrol/utils.cpp
deepin-devicemanager-server/deepin-devicecontrol/src/drivercontrol/utils.h
deepin-devicemanager-server/deepin-deviceinfo/src/mainjob.cpp
deepin-devicemanager-server/deepin-deviceinfo/src/mainjob.h
deepin-devicemanager/src/DriverControl/HttpDriverInterface.cpp
deepin-devicemanager/src/DriverControl/HttpDriverInterface.h

- Add version check logic for V25 system
- Update driver repository URL for V25 version
- Modify URL construction for driver requests
- Add getVersion and getOsBuild utility functions
Log: add V25 version support for driver repository

feat: add V25 version support for driver repository

---

deepin-devicemanager/src/DeviceManager/DeviceInfo.cpp
deepin-devicemanager/src/DriverControl/DriverScanner.cpp
deepin-devicemanager/src/DriverControl/HttpDriverInterface.cpp
deepin-devicemanager/src/Page/PageDriverManager.cpp
deepin-devicemanager/src/commonfunction.cpp
deepin-devicemanager/src/commonfunction.h

- Add trimming for vendor ID to remove whitespace
- Add fallback logic to parse VIDPID when vendor/model IDs are empty
Log: trim vendor ID and add VIDPID fallback parsing

fix: trim vendor ID and add VIDPID fallback parsing

---

deepin-devicemanager/src/DeviceManager/DeviceGpu.cpp
deepin-devicemanager/src/DeviceManager/DeviceManager.cpp
deepin-devicemanager/src/DeviceManager/DeviceManager.h
deepin-devicemanager/src/DeviceManager/DeviceNetwork.cpp
deepin-devicemanager/src/DeviceManager/DeviceNetwork.h

-- Local variable "items" shadows outer variable.
-- Function parameter should be passed by const reference.

Perf: [cppcheck] parameter should be passed by const reference.
